### PR TITLE
Conditionally display suggestion on duplicate course selection

### PR DESCRIPTION
**Pull request by inulty-dfe**
## Context

When a candidate has an open application to a course and the provider of that course only has one course available to apply to and the candidate tries to make a second application to that course, it doesn't make sense to suggest to the candidate to choose another course from the same provider.

## Changes proposed in this pull request

  Only suggest that the candidate choose another course from the
  provider if the provider has another course option available.

## Screenshot
Screenshot from 2023-09-29 12-42-15

## Guidance to review

Should we create a named scope on the `Course` model that selects all open and available courses in the current cycle?

### Review App

Single course added to the review app and [this user has been carried over](https://apply-review-8611.test.teacherservices.cloud/support/applications/40)

## Link to Trello card

[Trello Ticket](https://trello.com/c/tK9UOzqv/724-apply-hide-the-apply-to-a-different-course-if-the-provider-only-has-one-course)

## Things to check

- [x] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] If this code adds a column to the DB, decide whether it needs to be in analytics yml file or analytics blocklist
- [x] API release notes have been updated if necessary
- [x] If it adds a significant user-facing change, is it documented in the [CHANGELOG](CHANGELOG.md)?
- [x] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Review by JR-G — APPROVED** [review]
makes you realise the amount of scopes we need to call 😄

**Comment by lsalivonaite-transform** [comment]
Shouldn't there be a third condition for when the provider only has one course available, and it should display 'You can apply to a different training provider'?

**Comment by inulty-dfe** [comment]
> Shouldn't there be a third condition for when the provider only has one course available, and it should display 'You can apply to a different training provider'?

Yes, I did the opposite of the right thing. :100:

**Comment by lsalivonaite-transform** [comment]
Screenshot 2023-10-02 at 10 35 44
Need a full stop at the end of 'provider' other than that, I think it's all good!

**Review by lsalivonaite-transform — APPROVED** [review]

**Review by MaeveRoseveare — COMMENTED** [review]
The H1 looks a little intense. If it would be scope creep to change it, then ignore this. But if not I'd change it to remove the course name and provider name and mention it in the paragraph text instead:


**[H1] You already have an application for this course and training provider**

You already have an application for [course name] at [Provider name]. They only offer one course so you need to [apply to a different training provider](#).
_______________

Screenshot 2023-10-02 at 12 55 22

**Comment by inulty-dfe** [comment]
> The H1 looks a little intense. If it would be scope creep to change it, then ignore this. But if not I'd change it to remove the course name and provider name and mention it in the paragraph text instead:
> 
> **[H1] You already have an application for this course and training provider**
> 
> You already have an application for [course name] at [Provider name]. They only offer one course so you need to [apply to a different training provider](#).
> 
> Screenshot 2023-10-02 at 12 55 22

This does look good but I would like to get the changes on the ticket committed as there are other higher priorities at the moment.

**Pull request merged**
