### PR TITLE
Remove institution_name from other qualification

### PR DESCRIPTION
**Pull request by george-bit**
## Context

Removing institution from other qualification form and review screen as per request.  Also allowing country to show in it's place if international other qualification Feature Flag is turned on.

## Changes proposed in this pull request

Have removed institution_name form view, controller and updated component with logic to show country when relevant.

Before (feature flag on):

Before (feature flag off):

feature flag on:
image
image
image

feature flag off:
image
image
image

## Guidance to review

Check to see that other qualification no longer has institution and that country is displayed on the review when relevant.

## Link to Trello card

https://trello.com/c/H3qniVJ9/1853-remove-institution-for-non-degree-qualifications

## Things to check

- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by tvararu** [comment]
If you attempt to save this section, it errors because it says the qualification is incomplete:

Screenshot 2020-08-27 at 10 50 06

**Comment by george-bit** [comment]
Hi @paulrobertlloyd Added you as a reviewer on this one because of the UI change. Please can you have a check in the review app? :)

**Review by tvararu — APPROVED** [review]
💪

**Comment by paulrobertlloyd** [comment]
The fix and UI for this specific issue LGTM. Though in reviewing this, finding other bugs 😭

**Pull request merged**
