### PR TITLE
Add custom I18n exception handler in application.rb 

### PR DESCRIPTION
**Pull request by malcolmbaig**
## Context
We're already raising exceptions for missing locale strings when using
the `t` helper in views. Adding this additional config here will ensure
we also raise exceptions when locale strings for model attributes can't
be resolved.

## Changes proposed in this pull request
- Add the exception handler in application.rb 
- Fix a few missing locale string errors

## Guidance to review
- Ok for this to be applied to all environments?
- Do the fixes make sense? 

## Link to Trello card
https://trello.com/c/ouZ2DExb

## Things to check

- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] API release notes have been updated if necessary
- [ ] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training/blob/master/docs/environment-variables.md#azure-hosting-devops-pipeline)

### CODE REVIEW

**Review by stevehook — APPROVED** [review]
This makes sense. I'm not sure about switching this on in production, would be interested to know what others think. If we do so best to do a morning deploy and monitor any errors that may not be covered by tests.

**Comment by malcolmbaig** [comment]
> This makes sense. I'm not sure about switching this on in production, would be interested to know what others think. If we do so best to do a morning deploy and monitor any errors that may not be covered by tests.

Another option might be to just switch this on in QA and monitor for a few days before rolling out to prod.

@duncanjbrown @davidgisbey @cwrw - thoughts on enabling this exception handler in prod?

**Review by steventux — APPROVED** [review]
:+1: I'd agree with @stevehook this might need us to pay close attention to Sentry on deployment.

**Review by duncanjbrown — APPROVED** [review]
Makes sense to me!

**Review by cwrw — APPROVED** [review]
LGTM, I attempted a _questionable_ missing key scan for locale strings and it came back ok, so happy for this to be merged as long as we keep a watchful eye or two on Sentry as suggested.

**Pull request merged**
