### PR TITLE
Upgrade ruby and alpine

### PR DESCRIPTION
**Pull request by elceebee**
## Things to check

- [ ] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] If this code adds a column to the DB, decide whether it needs to be in analytics yml file or analytics blocklist
- [ ] API release notes have been updated if necessary
- [ ] If it adds a significant user-facing change, is it documented in the [CHANGELOG](CHANGELOG.md)?
- [ ] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Review by dcyoung-dev — APPROVED** [review]
Should we test this out on a review app before merging?

**Review by inulty-dfe — APPROVED** [review]
:rocket:

**Comment by tomas-stefano** [comment]
Is this PR good to go? 🚢

**Comment by inulty-dfe** [comment]
> Is this PR good to go? 🚢

I think it is, I was going to leave it for @elceebee to merge but it could go in now

**Pull request merged**
