### PR TITLE
use sslmod=require for database connection

### PR DESCRIPTION
**Pull request by vigneshmsft**
https://www.postgresql.org/docs/9.1/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS

## Changes proposed in this pull request
We have ssl enforced on the server, use the require mode on client as well.
use `sslmode=require`

## Things to check

- [x] This code doesn't rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by duncanjbrown** [comment]
Looks like docker-compose's postgres as-is doesn't support SSL. Which seems fair enough — dev envs shouldn't need to either. Maybe we should set this in prod only?

**Comment by vigneshmsft** [comment]
I'll try and enable ssl in docker-compose, unless we prefer to have it just in production?

**Comment by duncanjbrown** [comment]
> I'll try and enable ssl in docker-compose, unless we prefer to have it just in production?

I think it might be a bit of a pain to set up — & I'm not sure there's any advantage to having it in test?

**Comment by tvararu** [comment]
+1 for limiting this to prod only for now instead of adding SSL to docker-compose 👍

**Pull request merged**
