### PR TITLE
Remove .nvmrc and add to .gitignore

### PR DESCRIPTION
**Pull request by frankieroberto**
The node version specified in `.nvmrc` was in conflict with the one specified in `package.json`, as we forgot to update it.

Rather than keeping them in sync, we can remove the `.nvmrc` file and add it to `.gitignore` for any developers who want to continue to use this tool. Generally as a team we are moving towards [asdf](https://asdf-vm.com) anyway.

### CODE REVIEW

**Review by duncanjbrown — COMMENTED** [review]
Do we need this now we have directed `asdf` for all?

**Comment by frankieroberto** [comment]
> Do we need this now we have directed `asdf` for all?

Possibly not. I've not switched to asdf yet, but even so, we could remove it as it'd mean only having to set the node version in one place.

Is `asdf` smart enough to read the node version from `package.json` and the ruby version from `Gemfile`, or does it require a `.tool-versions` file?

**Comment by duncanjbrown** [comment]
`asdf` has a feature `legacy_version_file` (http://asdf-vm.com/manage/configuration.html#legacy-version-file) which has it read from `.ruby-version` or `.nvmrc` (or whatever) if not present. But this is a migration stopgap. All things being equal I would like to drop `.nvmrc` altogether as it's pure duplication.

`package.json` is a slightly different matter because it does have to duplicate the info — FWIW I think [this comment](https://github.com/asdf-vm/asdf-nodejs/issues/60#issuecomment-1008490151) is probably fair. BUT `yarn` will refuse to run if the `.tool-versions` and `package.json` versions are incompatible, with an error like this:

```
error apply-for-teacher-training@: The engine "node" is incompatible with this module. Expected version "^16.14.0". Got "16.13.0"
```

So given they have to be compatible or the project won't even build, I think it's ok to have the duplication. Tho it _is_ untidy. Removing `.nvmrc` would make it tidier.

**Comment by frankieroberto** [comment]
@duncanjbrown yeah that error (after running `nvm use`) was what alerted me to the discrepancy.

I’d agree that `asdf` and similar tools would ideally read the language version from the native dependency files (`package.json`, `Gemfile`, `requirements.txt` etc) where possible.

In the meantime, let’s remove `.nvmrc` and maybe even add it to `.gitignore`?

**Comment by frankieroberto** [comment]
@duncanjbrown pushed a commit to remove `.nvmrc` and add it to `.gitignore`. PR title and description updated.

**Review by duncanjbrown — APPROVED** [review]
👌

**Pull request merged**
