### PR TITLE
Add a changelog

### PR DESCRIPTION
**Pull request by frankieroberto**
This is a proposal for a "changelog" document within the codebase where we would briefly list any significant user-facing changes, and the dates on which they went live.

This could be useful as we often ship features incrementally behind a feature flag, and so it’s not always possible to tell from the GitHub history when something went live.

➡️  [Preview](https://github.com/DFE-Digital/apply-for-teacher-training/blob/changelog/CHANGELOG.md)

### CODE REVIEW

**Comment by carlosmartinez** [comment]
FWIW, I like the idea. @MylesJarvis @MaeveRoseveare whatchu thinkin

**Comment by frankieroberto** [comment]
@MylesJarvis @carlosmartinez I've added entries for the TTA sign up and the SKE course offer conditions. 

Let me know if you think we should merge this (and endeavour to keep it up to date) or abandon it!

**Comment by carlosmartinez** [comment]
If we keep it (and I think we should), we'll need some reliable way to remind ourselves to keep it up to date. Perhaps just adding another checkbox to the PR template.

**Comment by MaeveRoseveare** [comment]
Yes, I like it and can see the value with a lot going on and reminding ourselves what we did when. Good shout to add it to the checklist in the PR template. That would help me because I'll never remember to do this otherwise!

**Comment by frankieroberto** [comment]
Good idea to add it to the PR checklist. Although often the date something has gone 'live' hasn’t been the date we merged in the PR (as we’ve used the feature flags) - which is one reason the changelog might be useful! But at minimum we could always add a placeholder entry if we’re not sure when it’d go live.

There’s still a few historic changes missing from the changelog - but those might be lost to time, or at least require a bit more digging to work out what we did when.

**Comment by MylesJarvis** [comment]
I like this idea, and the thought to add it to the PR checklist as well. Let's ship it if we're content it gives a good enough flavour of recent changes

**Review by carlosmartinez — APPROVED** [review]

**Pull request merged**
