### PR TITLE
Remove 'free of charge' content from footer and Get help section on Apply

### PR DESCRIPTION
**Pull request by MaeveRoseveare**
## Context

We tell candidates to call our help number and beneath this we say 'free of charge' this is not free for international candidates. We've decided to remove this line from our footer and on the right hand side of the 'Your details' tab.

## Changes proposed in this pull request

Remove footer text
Remove content from right hand side bar on the 'Your details' tab

### Footer before:
Screenshot 2023-11-22 at 15 57 27

### Footer after:
Screenshot 2023-11-22 at 16 42 48

### Right hand info before:
Screenshot 2023-11-22 at 15 57 35

### Right hand info after:

Screenshot 2023-11-22 at 16 42 58

## Link to Trello card

[](https://trello.com/c/ExTBmged/701-free-of-charge-phone-number-content-is-misleading)

## Things to check

- [ ] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] If this code adds a column to the DB, decide whether it needs to be in analytics yml file or analytics blocklist
- [ ] API release notes have been updated if necessary
- [ ] If it adds a significant user-facing change, is it documented in the [CHANGELOG](CHANGELOG.md)?
- [ ] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Review by avinhurry — APPROVED** [review]
Looks good, do we need to update Find too?

image

**Comment by MaeveRoseveare** [comment]
["Free of charge" phone number content is misleading for International candidates](https://trello.com/c/ExTBmged/701-free-of-charge-phone-number-content-is-misleading-for-international-candidates)

**Comment by MaeveRoseveare** [comment]
> Looks good, do we need to update Find too?
> 
> image

@avinhurry yes, Myles did a PR a while ago but closed it. I don't know how to reopen it, if you'd like to help? :) https://github.com/DFE-Digital/publish-teacher-training/pull/3812

**Comment by avinhurry** [comment]
> > Looks good, do we need to update Find too?
> > image
> 
> @avinhurry yes, Myles did a PR a while ago but closed it. I don't know how to reopen it, if you'd like to help? :) [DFE-Digital/publish-teacher-training#3812](https://github.com/DFE-Digital/publish-teacher-training/pull/3812)

Ah great. I've re-opened and rebased it.

**Review by MylesJarvis — APPROVED** [review]
LGTM

**Pull request merged**
