### PR TITLE
Fix provider permissions indicators for disabled permissions

### PR DESCRIPTION
**Pull request by steventux**
## Context

The providers listed for disabled permissions is displaying the incorrect side of the permissions relationship.

## Changes proposed in this pull request

- Display the training provider when viewing a ratifying provider and the training provider doesn't have the relevant permissions.
- Display the ratifying provider when viewing a training provider and the ratifying provider doesn't have the relevant permissions.
- Rename `CrossIcon` to `CrossIconComponent`

## Link to Trello card

Spotted in support

## Things to check

- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by duncanjbrown** [comment]
I think the behaviour here isn't quite right yet. If I set permissions like this, ie Blackfriars can do everything everywhere:

Screenshot 2020-11-11 at 12 30 48

Then I see this in the component:

Screenshot 2020-11-11 at 12 30 39

Shouldn't I see that this applies to courses ratified by those providers?

And if I set the reverse (ie untick the whole left column, tick the whole right) I get this:

Screenshot 2020-11-11 at 12 33 02

**Comment by steventux** [comment]
@duncanjbrown updated to use subtraction of `*_providers_that_can_*` to determine providers with disabled permissions.

**Comment by AgaDufrat** [comment]
I may be massively confused by this but I tried the following scenario (that came through support).
- Ratifying providers have all the permissions, training provider (Blackfriars) doesn't have any permissions.
<kbd>Screenshot 2020-11-19 at 14 07 01</kbd>

This is what I see on the user's page:
<kbd>Screenshot 2020-11-19 at 13 59 33</kbd>


It feels like it's the wrong way round:
- Blackfriars can make decisions (as it's a user level permission) but it *does not apply* to courses ratified by (...)
- Keele can make decisions and it *applies to* courses run by Blackfriars

**Comment by benswannack** [comment]
Closing this PR as superseded by https://github.com/DFE-Digital/apply-for-teacher-training/pull/3523

**Pull request closed without merging**
