### PR TITLE
Make magic links single-use

### PR DESCRIPTION
**Pull request by malcolmbaig**
## Context

Magic links currently last for one hour, with no limit on their use
during that time. A recent pentest recommended that we make magic links
single-use.
## Changes proposed in this pull request

- Expire the token after a successful sign in.
- Amend the copy on the expired page to reflect the new behaviour.
## Link to Trello card

https://trello.com/c/aNcIaroP

## Things to check

- [ ] This code doesn't rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] API release notes have been updated if necessary
- [ ] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by malcolmbaig** [comment]
@tijmenb @tvararu was thinking something like this. WDYT?

**Comment by benilovj** [comment]
On the [Get Help With Tech service](https://get-help-with-tech.education.gov.uk), we hit an issue with single use magic links that's worth being aware of, in case it starts happening when this is merged:

https://github.com/DFE-Digital/get-help-with-tech/pull/149

We saw these issues with users from 2 local authorities but we only had a small number of LAs on the service at the time, so it was hard to gauge the actual scale of the problem.

**Comment by edwardhorsford** [comment]
I believe Notify also implemented an interstitial because of email clients pre-visiting links.

**Comment by malcolmbaig** [comment]
@benilovj @edwardhorsford thanks for your comments, adding the additional step definitely makes sense. I'll update the PR :+1:

**Pull request closed without merging**
