### PR TITLE
Migration to add fee and salary information to courses

### PR DESCRIPTION
**Pull request by avinhurry**
## Context

In preperation for #6879 we need to add some new columns to the `Courses` table. We will merge this seperately first, in this PR.

## Changes proposed in this pull request

 - Migration to add the following columns to the `Courses` table on the `Apply` database: `fee_details`, `fee_international`, `fee_domestic` and `salary_details`

- Add these columns to `Analytics.yml`

## Link to Trello card

https://trello.com/c/iUZlrEGv/4689-migration-to-add-fee-and-salary-information-to-courses

## Things to check

- [x] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Review by frankieroberto — APPROVED** [review]

**Review by stevehook — APPROVED** [review]
Looks good. Dumb question: Do they vary according whether a course is part-time or full? It looks like TTAPI only stores fees associated with courses (rather than site) but courses in TTAPI have a study mode so I'm not sure.

**Comment by frankieroberto** [comment]
> Looks good. Dumb question: Do they vary according whether a course is part-time or full? It looks like TTAPI only stores fees associated with courses (rather than site) but courses in TTAPI have a study mode so I'm not sure.

Not a dumb question! I don’t know the answer though… I have a hunch that long-term we should force all courses to be either full time or part time (not both), to make this less ambiguous.

**Comment by stevehook** [comment]
> > Looks good. Dumb question: Do they vary according whether a course is part-time or full? It looks like TTAPI only stores fees associated with courses (rather than site) but courses in TTAPI have a study mode so I'm not sure.
> 
> Not a dumb question! I don’t know the answer though… I have a hunch that long-term we should force all courses to be either full time or part time (not both), to make this less ambiguous.

seen on Find...

image

Having single-study-mode courses sounds like a good idea.

**Comment by avinhurry** [comment]
> > > Looks good. Dumb question: Do they vary according whether a course is part-time or full? It looks like TTAPI only stores fees associated with courses (rather than site) but courses in TTAPI have a study mode so I'm not sure.
> > 
> > 
> > Not a dumb question! I don’t know the answer though… I have a hunch that long-term we should force all courses to be either full time or part time (not both), to make this less ambiguous.
> 
> seen on Find...
> 
> image
> 
> Having single-study-mode courses sounds like a good idea.

Yeah defo not a dumb question. As far as I know we were previously encouraging providers to create one course as `full_time_or_part_time` on Publish rather than two seperate courses, one `full_time` and one `part_time`. Quite a few providers wanted to create two seperate courses for their own accounting reasons, so maybe that is worth a rethink...

**Pull request merged**
