### PR TITLE
can't remove hint text

### PR DESCRIPTION
**Pull request by EmmaFrith**
I tried to delete the hint text here (because the current hint text doesn't make sense) but doing so broke Apply locally. 

Does that mean it's not as simple as deleting the line?

Can a dev help? 

Screenshot 2022-03-23 at 15 03 04

### CODE REVIEW

**Comment by JonF1** [comment]
You'll also need to remove where that message is being called - looks like here https://github.com/DFE-Digital/apply-for-teacher-training/blob/main/app/views/candidate_interface/restructured_work_history/review/show.html.erb#L29 and here https://github.com/DFE-Digital/apply-for-teacher-training/blob/main/app/views/candidate_interface/work_history/review/show.html.erb#L20.

**Comment by JonF1** [comment]
You'll also need to remove where that message is being called - looks like here https://github.com/DFE-Digital/apply-for-teacher-training/blob/main/app/views/candidate_interface/restructured_work_history/review/show.html.erb#L29 and here https://github.com/DFE-Digital/apply-for-teacher-training/blob/main/app/views/candidate_interface/work_history/review/show.html.erb#L20.

**Comment by MylesJarvis** [comment]
I'm curious to know why we have a `work_history` and `restructured_work_history` yml file. Anyone got any intel?

**Comment by MylesJarvis** [comment]
The one that renders on Prod is `restructured_work_history`, so can we excise the other one from the codebase?

**Comment by MylesJarvis** [comment]
I've attempted to fix this - I think we accidentally re-use this helptext on the complete page, as opposed to solely here, so we may not want to remove it specifically?

**Review by JonF1 — APPROVED** [review]

**Comment by duncanjbrown** [comment]
> I think we can probably remove the old work history flow now? We had to keep it around last cycle as anyone who started their application with the old flow was still using it. But since then we should be 100% in the new flow, even for those who rolled over their application from last cycle. I think.

Yes - let's delete!

**Comment by MylesJarvis** [comment]
@JonF1 @duncanjbrown can we re-run the github actions to build a preview app?

**Comment by MylesJarvis** [comment]
Screenshot 2022-03-24 at 11 01 00

Appears to be working fine @EmmaFrith

**Comment by EmmaFrith** [comment]
thank you @JonF1 and @MylesJarvis - LGTM. shall we merge?

**Pull request merged**
