### PR TITLE
DNM - Upgrade webpacker

### PR DESCRIPTION
**Pull request by tomas-stefano**
## Context

Upgrading webpacker to fix security issues.

### CODE REVIEW

**Comment by tomas-stefano** [comment]
[Security vulnerabilities on the apply repo](https://trello.com/c/JvMY8OAE/1419-security-vulnerabilities-on-the-apply-repo)

**Comment by frankieroberto** [comment]
@tomas-stefano should we create a follow-up ticket to explore moving away from Webpacker, given that [it has been retired](https://github.com/rails/webpacker#webpacker-has-been-retired-)?

**Comment by tomas-stefano** [comment]
> @tomas-stefano should we create a follow-up ticket to explore moving away from Webpacker, given that [it has been retired](https://github.com/rails/webpacker#webpacker-has-been-retired-)?

We have one https://trello.com/c/86vHtNWF/1117-replace-webpacker (But it is empty!)

**Comment by tomas-stefano** [comment]
Closing this in favor of the card to replace webpacker

**Pull request closed without merging**
