### PR TITLE
Bug Fix: clicking on option divs always selected first option when e

### PR DESCRIPTION
**Pull request by elceebee**
## Context

GIVEN I am a provider rejecting a candidate's application
WHEN I select Continue
THEN I see an error
WHEN I select any reason (clicking on the div rather directly on the input)
THEN the *first* reason is selected, regardless of which one I have selected

Note this only happened if you clicked on the text (ie, the surrounding div), rather than the actual checkbox.

## Changes proposed in this pull request

We had `link_error = true` for all of the options, which meant they did not have distinct ids on the input. This PR just inks the first option. 

| Before | After |
| ------ | ------ |
| https://github.com/user-attachments/assets/63b980f8-7391-4f65-a168-3f9eccfaeba3 | https://github.com/user-attachments/assets/109fcee7-a231-4dc8-98cf-fa1f41fb2144 |

## Guidance to review

You can test it locally or on the review app by rejecting a candidate and following the steps in the context above.

## Things to check

- [ ] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] If this code adds a column to the DB, decide whether it needs to be in analytics yml file or analytics blocklist
- [ ] API release notes have been updated if necessary
- [ ] If it adds a significant user-facing change, is it documented in the [CHANGELOG](CHANGELOG.md)?
- [ ] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)
- [ ] Inform data insights team due to database changes
- [x] Make sure all information from the Trello card is in here
- [x] Rebased main
- [x] Cleaned commit history
- [x] Tested by running locally
- [x] Add PR link to Trello card

### CODE REVIEW

**Comment by elceebee** [comment]
[Bug: Rejection reason checkbox labels not working when validation message shown](https://trello.com/c/kCMUC2sb/475-bug-rejection-reason-checkbox-labels-not-working-when-validation-message-shown)

**Review by avinhurry — APPROVED** [review]
I tested your fix locally and it works well. 

I found another bug on the same page (unrelated to your PR)

If you open all the radios and submit you get a translation failure. I think there's a missing translation.

image

**Comment by elceebee** [comment]
> I tested your fix locally and it works well.
> 
> I found another bug on the same page (unrelated to your PR)
> 
> If you open all the radios and submit you get a translation failure. I think there's a missing translation.
> 
> image

Great catch, I'll have a look and see if I can roll the fix into this PR. If it's something. more than a missing translation, I'll create a ticket.

**Review by PeteWilliams — APPROVED** [review]
Appears to now to be working as intended 🙌

**Pull request merged**
