### PR TITLE
Further content updates to the references section

### PR DESCRIPTION
**Pull request by JR-G**
## Context

These are further changes to the new references section, following UR sessions.

## Changes proposed in this pull request

Copy update for when the candidate has not yet received a reference (the link text has also been updated):
|Before|After|
|---|---|
|image|image|

Conditionally change the section advice:
|No references received|Two (or more) references received|Section completed|
|---|---|---|
|image|image|image|

Updated email copy:
|Received 2 references|Received 3 or more references|Already selected 2 and another comes in|
|---|---|---|
|image|image|image|

Copy change for 'Choose your referees' guidance:
|Before|After|
|---|---|
|image|image|

Copy change for guidance:
|Before|After|
|---|---|
|image|image|

## Guidance to review

Refer to the Google Doc attached to the Trello ticket for the requested changes

## Link to Trello card

https://trello.com/c/yLQLuKz1

## Things to check

- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] API release notes have been updated if necessary
- [ ] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Review by malcolmbaig — APPROVED** [review]

**Review by davidgisbey — APPROVED** [review]

**Comment by EmmaFrith** [comment]
spotted a typo here: 

- give you a full reference – providers need to know if you’re a suitable to become a teacher

remove 'a' 

@JR-G @B-Bonner

**Comment by EmmaFrith** [comment]
Screenshot 2021-07-06 at 11 41 34

could we try the task list copy as inset text so it feels a bit more structured? https://design-system.service.gov.uk/components/inset-text/

thoughts @paulrobertlloyd?

**Comment by EmmaFrith** [comment]
re. this setence: 

'The Apply service will not accept references sent to providers over email.'

We don't tend to refer to ourselves as 'the Apply service' - could we think of something different? For example:

'References sent to providers by email will not be accepted.'

@B-Bonner @JR-G

**Comment by EmmaFrith** [comment]
upon adding 1 referee, the task list action changes from 'Add your references' to 'Manage your references'. I think it should stay as 'Add your references' - at least until you get 2. 

Screenshot 2021-07-06 at 11 53 52

**Comment by EmmaFrith** [comment]
Screenshot 2021-07-06 at 11 59 45
I've added 2 references - normally we should see inset text at the top enabling you to keep adding more references? Is this a bug? 

@JR-G @B-Bonner

**Comment by EmmaFrith** [comment]
There seems to be some contracting information in different areas in the service - on the task list copy we say 'when you've received your references, you can select which 2 to submit with your application'. But here (see screenshot) we say 'We’ll cancel any remaining requests when you’ve received 2 references.'

Screenshot 2021-07-06 at 12 05 41

@B-Bonner @JR-G

**Comment by EmmaFrith** [comment]
Screenshot 2021-07-06 at 12 07 55
The system isn't allowing me to request more than 2 references.

**Comment by EmmaFrith** [comment]
How about making these 2 bits of content consistent? 

Screenshot 2021-07-06 at 12 30 15

Screenshot 2021-07-06 at 12 31 32

**Comment by EmmaFrith** [comment]
the second reference email received email says this:
Screenshot 2021-07-06 at 12.37.27.png 

and the 3rd reference received email says this:

Screenshot 2021-07-06 at 12.38.13.png

but technically, if we're sticking with the current system where you can select 2 after receiving only 2 - the message 'Sign in and select 2 references to submit with your application' should start to appear in emails after the 2nd ref received.

**Comment by B-Bonner** [comment]
> How about making these 2 bits of content consistent?
> 
> Screenshot 2021-07-06 at 12 30 15
> 
> Screenshot 2021-07-06 at 12 31 32
> 
> Perhaps: 'Once you’ve received 2 or more references, you need to select which 2 to include in your application.'
> 
> @B-Bonner @JR-G

Yeah. How about using the version on the dashboard for 'Select 2 references'?

**Comment by B-Bonner** [comment]
> the second reference email received email says this:
> 
> Screenshot 2021-07-06 at 12 41 24
> 
> and the 3rd reference received email says this:
> 
> Screenshot 2021-07-06 at 12 41 10
> 
> but technically, if we're sticking with the current system where you can select 2 after receiving only 2 - the message 'Sign in and select 2 references to submit with your application' should start to appear in emails after the 2nd ref received.
> 
> @B-Bonner @JR-G

Yep. In that case, we only need to change the 'Sign in' call to action in the 2 references received email to read 'Sign in and select 2 references to submit with your application'.

**Review by B-Bonner — COMMENTED** [review]
Could we try moving this line to the 'Select 2 references' section?

Screenshot 2021-07-06 at 16 23 38

**Review by B-Bonner — APPROVED** [review]

**Review by B-Bonner — APPROVED** [review]

**Review by B-Bonner — APPROVED** [review]

**Review by EmmaFrith — APPROVED** [review]
great work @JR-G !

**Pull request merged**
