### PR TITLE
Extract TestSuiteTimeMachine into its own gem

### PR DESCRIPTION
**Pull request by elliotcm**
## Context

Hello all.  Back on Apply I created this library and the plan was always to extract it to a gem, but I never got round to it.

Today my combination of personal need and civic duty is your gain.

## Changes proposed in this pull request

I've hooked the [new gem](https://github.com/SmartCasual/test_suite_time_machine) in place of the class that was in `lib` previously.  Nothing in the interface or usage has changed.

## Guidance to review

I ran a couple of spot checks, but not the whole suite.  I don't know if this external PR will trigger the whole suite, but worth running it one way or another.

I also found that the following changes were required to get the devcontainer to work:
```diff
diff --git a/.env.test b/.env.test
index a5e6df392..167467d7d 100644
--- a/.env.test
+++ b/.env.test
@@ -1,4 +1,4 @@
-REDIS_URL=redis://localhost:6379/9
+REDIS_URL=redis://redis:6379/9
 TEACHER_TRAINING_API_BASE_URL=http://teacher-training-api-test/api/v1
 HOSTING_ENVIRONMENT_NAME=test
 STATE_CHANGE_SLACK_URL=https://example.com/slack-webhook
@@ -13,3 +13,7 @@ GOOGLE_TAG_MANAGER_APPLY=GTM-APPLY-XX
 GOOGLE_TAG_MANAGER_MANAGE=GTM-MANAGE-XX
 BULLET=false
 COVERAGE=false
+GOVUK_NOTIFY_API_KEY=
+DB_HOSTNAME=postgres
+DB_USERNAME=postgres
+DB_PASSWORD=postgres
```
I didn't include them here as they're probably best done via the docker compose file and I didn't want to get into the weeds with it.

### CODE REVIEW

**Comment by inulty-dfe** [comment]
Hi Elliott,

I'm wondering why we shouldn't just use [`ActiveSupport::Testing::TimeHelper`s](https://api.rubyonrails.org/classes/ActiveSupport/Testing/TimeHelpers.html) instead of depending on Timecop?

**Comment by elliotcm** [comment]
> Hi Elliott,
> 
> I'm wondering why we shouldn't just use [`ActiveSupport::Testing::TimeHelper`s](https://api.rubyonrails.org/classes/ActiveSupport/Testing/TimeHelpers.html) instead of depending on Timecop?

Hi @inulty-dfe 

Not a conscious decision; I went with timecop because a) it's what I was familiar with, b) it's what Apply was already using, and c) I didn't know Rails had written their own.

Certainly TSTM could be made to use these helpers if available, but I wouldn't say it would be appropriate to require them in the gem since then you're depending on ActiveSupport.

Perhaps a good candidate for a PR on TSTM itself, if you're keen to remove Timecop from Apply?

**Comment by inulty-dfe** [comment]
Absolutely, I don't think requiring AS in a tiny gem just for the TestHelpers is a good idea. And since this is all test dependencies it probably doesn't matter too much.

But for this application, a Rails application, I think the most sensible thing to do is to find and replace the  TSTM methods with the TimeHelpers

**Comment by elliotcm** [comment]
Bear in mind that TSTM is providing interface and functionality on top of timecop, and so it would similarly provide that on top of the AS timehelpers.  You can't replace TSTM's helpers with the ActiveSupport ones without losing the purpose of TSTM (as then you're just going back to what Apply had before, with plain Timecop calls).  TSTM and Timecop/AS::TimeHelpers are not 1:1 interfaces.

I would suggest your three options are:
1. Stick with the Timecop dependency, at least for now
2. Add a PR in to TSTM to use ActiveSupport's helpers if available
3. Remove TSTM and replace with TimeHelpers

I would not recommend option 3 without fully understanding why it was added in the first place, but ultimately that's up to you now :)

**Comment by elliotcm** [comment]
I guess option 4 is "ignore this PR entirely" which is also totally reasonable, but does leave you maintaining that bit of code yourselves, one way or the other.

**Comment by JR-G** [comment]
Adding the blocked label for now – we'll come back to this after we've completed the start of the new cycle!

**Pull request closed without merging**
