### PR TITLE
Refactoring to reduce Metrics/PerceivedComplexity cop errors

### PR DESCRIPTION
**Pull request by despo**
## Context
Addressing Metrics/PerceivedComplexity cop issues so we can eventually enable the cop.
40 or so to go..

## Link to Trello card
https://trello.com/c/I6JiD7cR/3856-rubocop-cleanup

## Things to check

- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Comment by duncanjbrown** [comment]
Not a massive fan of these cops as they make taste decisions for us. Please could we hold off on this one for the time being?

**Comment by cwrw** [comment]
@duncanjbrown For this particular cop I can see how it can help us with long complex methods, which we do tend to have. I had a look through the changes proposed and didn't find anything particularly opinionated other than breaking out longer/complex methods. 

I propose we have a chat, maybe with the wider team around the cops that we are worried about and why?

**Review by cwrw — COMMENTED** [review]
Update: discussed in person and we're ok to go ahead with those cop changes where if they become a problem we can disable them in the future. Im happy to ✅ @duncanjbrown any further thoughts on this?

**Comment by duncanjbrown** [comment]
Yep - let's merge!

**Review by cwrw — APPROVED** [review]

**Pull request merged**
