### PR TITLE
Remove implementation of wizard to use the dfe-wizard gem

### PR DESCRIPTION
**Pull request by tomas-stefano**
## Context

We need to have the same wizard logic under Publish so the work we did on continuous applications last year were extracted to this gem:

This work was extracted to https://github.com/DFE-Digital/dfe-wizard

Now that the first version of the gem is released I can add on Apply and next week on Publish.

## Changes proposed in this pull request

The main changes of extracting was because of gem organisation the classes were renamed:

* DfE::Wizard became DfE::Wizard::Base
* DfE::WizardStep became DfE::Wizard::Step
* DfE::WizardStore became DfE::Wizard::Store

So this work, adds the gem and rename the classes

## Guidance to review

This work touches on the most important form of Apply: the actual candidate applying for a course.

Even with the automated tests guaranteeing that everything work I totally advise (myself included on this) to apply for a course in the review app and play around on different choices under the submission wizard.

## Link to Trello card

No trello card but an internal dependency needed to add the A-levels Page to Publish: https://trello.com/c/GCHIarVq/1767-a-levels-1-7-add-a-level-requirements-question-page-for-tda-courses-on-publish?filter=label:Epic%3A%20TDA

## Things to check

- [ ] Does apply submission work?
- [ ] Does apply submission work within the many choices candidate can make?

### CODE REVIEW

**Review by CatalinVoineag — APPROVED** [review]
👍🏻 🗑️

**Review by inulty-dfe — CHANGES_REQUESTED** [review]
Avoiding this getting merged too fast

**Review by inulty-dfe — APPROVED** [review]
I've tested most scenarios on the deploy app.

**Comment by tomas-stefano** [comment]
Awesome! Thank you 🙏. I will also take a brief look tomorrow and merge.

**Pull request merged**
