### PR TITLE
Add separate steps for degree award and graduation years

### PR DESCRIPTION
**Pull request by george-bit**
## Context

As per discussion on #5207, it was decided that stylistically we should break the degree yar page into two separate pages.

## Changes proposed in this pull request

start year page
image

award page (if degree completed)
image

award page (if degree not completed)
image

## Guidance to review

Test functionality in review app.

Thoughts on the conditonal titles on the award page?

## Link to Trello card

https://trello.com/c/X6kVc0mW/3724-break-out-degree-award-year-and-graduation-year-into-two-steps-in-the-degree-flow

## Things to check

- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Review by paulrobertlloyd — CHANGES_REQUESTED** [review]
Check [the Google Doc](https://docs.google.com/document/d/1JsjkjfM2BZskRNgyLJMK_qL7rgYWPrkcP2IqjXTlcTw/) for the revised content changes. Note that the page heading is now also the form label. So, for example:

**What year did you start your degree?**
_For example, 2018_

[________]

**Comment by george-bit** [comment]
My bad @paulrobertlloyd, I don't seem to have access to the google doc. Shouldn't be a big change though.

**Comment by paulrobertlloyd** [comment]
Not sure if this was the case before, but I can enter a start and graduation dates in the future (aka 2022) without having these validated.

Also, separate bug I suspect, but for grade, ‘Other’ is always pre-selected, when it shouldn’t be:

Screenshot 2021-08-09 at 17 29 53

**Comment by george-bit** [comment]
> Not sure if this was the case before, but I can enter a start and graduation dates in the future (aka 2022) without having these validated.
> 
> Also, separate bug I suspect, but for grade, ‘Other’ is always pre-selected, when it shouldn’t be:
> 
> Screenshot 2021-08-09 at 17 29 53

I think this was the case before as I've not altered any of the validations but just broken them up into a separate forms. 

This PR is getting pretty big now and was just regarding so I'm slightly reluctant to address these issues here. Would it be possible to card these two issues up as bugs and I'll pick them up this week?

**Comment by paulrobertlloyd** [comment]
I’ll write up a card for the ‘Other’ pre-selection.

As to the year validation, maybe just check with @JR-G, because I thought that’s what we did add in the commit that preceded this, but I may be mistaken.

**Comment by JR-G** [comment]
> I’ll write up a card for the ‘Other’ pre-selection.
> 
> As to the year validation, maybe just check with @JR-G, because I thought that’s what we did add in the commit that preceded this, but I may be mistaken.

The main validation I added in that PR was to stop candidates from being able to enter an award year in the past, if they had marked the degree as incomplete

**Comment by george-bit** [comment]
I think there is validation to prevent adding an award year after the next cycle begins if the degree is incomplete . However, for  completed degrees there's no future year validation. I can add this if suits?

**Comment by paulrobertlloyd** [comment]
> The main validation I added in that PR was to stop candidates from being able to enter an award year in the past, if they had marked the degree as incomplete.

Ahh, that was it!

> However, for completed degrees there's no future year validation. I can add this if suits?

There might be a reason why we decided not validate these dates, so let’s pick up separately.

**Review by paulrobertlloyd — APPROVED** [review]

**Pull request merged**
