### PR TITLE
Proposal for redacting personal data

### PR DESCRIPTION
**Pull request by elceebee**
## Context

We would like to be able to use production data locally, especially during incidents. In order to do this we need to decide what fields should be anonymised in the production db dump.

## Changes proposed in this pull request

- Draft ADR

Next steps would be actually writing the script to anonymise the data and working with infra to create the production dump.

## Guidance to review

Have a look at this list and the schema. Is there anything else we should include? 

## Things to check

- [ ] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] If this code adds a column to the DB, decide whether it needs to be in analytics yml file or analytics blocklist
- [ ] API release notes have been updated if necessary
- [ ] If it adds a significant user-facing change, is it documented in the [CHANGELOG](CHANGELOG.md)?
- [ ] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)
- [ ] Inform data insights team due to database changes
- [x] Make sure all information from the Trello card is in here
- [ ] Rebased main
- [ ] Cleaned commit history
- [ ] Tested by running locally
- [x] Add PR link to Trello card

### CODE REVIEW

**Comment by elceebee** [comment]
[Determine which personal data fields we wish to redact for local DB copies/backups](https://trello.com/c/LsYzfkER/423-determine-which-personal-data-fields-we-wish-to-redact-for-local-db-copies-backups)

**Review by avinhurry — APPROVED** [review]
I'd love to have this, it will be so useful!

**Review by CatalinVoineag — APPROVED** [review]
Good work!

**Comment by carlosmartinez** [comment]
Looks pretty sensible to me. Register's [sanitise.sql](https://github.com/DFE-Digital/register-trainee-teachers/blob/main/db/scripts/sanitise.sql) might be useful. This is run as part of the build, so there's always a sanitised version of the data ready for download.

One consideration is how to ensure this is kept up-to-date. Maybe _another_ PR checklist item?

**Review by dcyoung-dev — APPROVED** [review]
Love it 🤩

**Comment by elceebee** [comment]
> Looks pretty sensible to me. Register's [sanitise.sql](https://github.com/DFE-Digital/register-trainee-teachers/blob/main/db/scripts/sanitise.sql) might be useful. This is run as part of the build, so there's always a sanitised version of the data ready for download.
> 
> One consideration is how to ensure this is kept up-to-date. Maybe _another_ PR checklist item?

Good shout. I'll add the PR checklist item to the next ticket. And thanks for the script. That will save me some time getting started!

**Pull request merged**
