### PR TITLE
Fix find opens integration test failures

### PR DESCRIPTION
**Pull request by inulty-dfe**
## Context

Tests are failing when the test time is in after apply opens in the continuous applications recruitment cycle (2024).

## Changes proposed in this pull request

When the current time is in the new recruitment cycle for continuous applications, many of the existing tests fail. This is because some of the test helpers only work in legacy applications flow. 

Once we are past apply opens in the new recruitement cycle 2024 we can do a wholesale update to the tests and remove all legacy flows and helpers.

### Checklist 

**integration_shared, on**

- [x] ./spec/system/register_api/register_receives_application_spec.rb:8
- [x] ./spec/system/inactive_application_spec.rb:6

**integration_shared, off**

- [x] ./spec/system/inactive_application_spec.rb:6

**integration_provider, on**

- [x] ./spec/system/provider_interface/provider_acts_as_candidate_on_sandbox_spec.rb:7

**integration_candidate, on**

 - [x] ./spec/system/candidate_interface/adviser_sign_up/candidate_signs_up_for_an_adviser_spec.rb:8
 - [x] ./spec/system/candidate_interface/entering_details/candidate_entering_gcse_science_award_spec.rb:6
 - [x] ./spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_course_selection_section_spec.rb:7
 - [x] ./spec/system/candidate_interface/rejection/deleting_a_reason_for_rejection_does_not_impact_the_candidate_interface_spec.rb:4
 - [x] ./spec/system/candidate_interface/entering_details/candidate_entering_gcse_spec.rb:6
 - [x] ./spec/system/candidate_interface/feedback/candidate_completes_the_feedback_form_spec.rb:6
 - [x] ./spec/system/candidate_interface/continuous_applications/withdraws/candidate_withdraws_spec.rb:18
 - [x] ./spec/system/candidate_interface/entering_details/candidate_viewing_a_science_gcse_spec.rb:6
 - [x] ./spec/system/candidate_interface/continuous_applications/course_selection/candidate_edits_course_choices_spec.rb:7
 - [x] ./spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_contact_details_section_spec.rb:6
 - [x] ./spec/system/candidate_interface/rejection/candidate_reviews_reasons_for_rejection_spec.rb:4
 - [x] ./spec/system/candidate_interface/course_selection/candidate_does_not_know_where_they_want_to_apply_spec.rb:6
 - [x] ./spec/system/candidate_interface/course_selection/candidate_sees_add_additional_courses_after_adding_course_spec.rb:7
 - [x] ./spec/system/candidate_interface/submitting/candidate_reviews_application_and_completes_equality_and_diversity_spec.rb:6
 - [x] ./spec/system/candidate_interface/signup_and_signin/candidate_email_tracking_spec.rb:6
 - [x] ./spec/system/candidate_interface/course_selection/candidate_edits_course_choices_spec.rb:7
 - [x] ./spec/system/candidate_interface/references/candidate_carries_over_unsubmitted_application_spec.rb:6
 - [x] ./spec/system/candidate_interface/offers_and_withdrawals/candidate_withdraws_spec.rb:18
 - [x] ./spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_personal_details_section_spec.rb:6
 - [x] ./spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_adjustments_section_spec.rb:6
 - [x] ./spec/system/candidate_interface/references/candidate_submits_a_duplicate_application_spec.rb:6
 - [x] ./spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_unpaid_experience_section_spec.rb:6
 - [x] ./spec/system/candidate_interface/references/candidate_request_references_spec.rb:6
 - [x] ./spec/system/candidate_interface/course_selection/sandbox_user_apply_from_find_spec.rb:6
 - [x] ./spec/system/candidate_interface/entering_details/candidate_completes_contact_details_with_a_missing_address_feature_flag_disabled_spec.rb:6
 - [x] ./spec/system/candidate_interface/course_selection/candidate_selecting_a_course_spec.rb:6
 - [x] ./spec/system/candidate_interface/signup_and_signin/candidate_views_guidance_from_unsubmitted_application_spec.rb:6
 - [x] ./spec/system/candidate_interface/submitting/candidate_reviewing_application_with_unavailable_course_options_spec.rb:6
 - [x] ./spec/system/candidate_interface/submitting/candidate_submits_application_with_full_course_study_mode_spec.rb:6
 - [x] ./spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_personal_statement_section_spec.rb:6
 - [x] ./spec/system/candidate_interface/guidance/public_user_spec.rb:4
 - [x] ./spec/system/candidate_interface/continuous_applications/course_selection/backlinks_spec.rb:7
 - [x] ./spec/system/candidate_interface/signup_and_signin/candidate_signs_in_with_the_penultimate_valid_token_spec.rb:6
 - [x] ./spec/system/candidate_interface/submitting/candidate_submits_application_with_a_removed_site_spec.rb:6
 - [x] ./spec/system/candidate_interface/continuous_applications/course_selection/candidate_deletes_application_spec.rb:6
 - [x] ./spec/system/candidate_interface/course_selection/candidate_deletes_course_after_completing_section_spec.rb:6
 - [x] ./spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_qualifications_spec.rb:6
 - [x] ./spec/system/candidate_interface/continuous_applications/submitting/redirect_to_your_applications_spec.rb:6
 - [x] ./spec/system/candidate_interface/continuous_applications/submitting/redirect_to_your_applications_spec.rb:18
 - [x] ./spec/system/candidate_interface/continuous_applications/submitting/redirect_to_your_applications_spec.rb:12
 - [x] ./spec/system/candidate_interface/submitting/international_candidate_submitting_application_spec.rb:7
 - [x] ./spec/system/candidate_interface/entering_details/candidate_entering_english_gcse_spec.rb:6

**integration_candidate, off**

 - [x] ./spec/system/candidate_interface/continuous_applications/course_selection/backlinks_spec.rb:7
 - [x] ./spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_personal_statement_section_spec.rb:6
 - [x] ./spec/system/candidate_interface/continuous_applications/submitting/redirect_to_your_applications_spec.rb:12
 - [x] ./spec/system/candidate_interface/continuous_applications/submitting/redirect_to_your_applications_spec.rb:6
 - [x] ./spec/system/candidate_interface/continuous_applications/submitting/redirect_to_your_applications_spec.rb:18
 - [x] ./spec/system/candidate_interface/guidance/public_user_spec.rb:4
 - [x] ./spec/system/candidate_interface/references/candidate_request_references_spec.rb:6
 - [x] ./spec/system/candidate_interface/signup_and_signin/candidate_views_guidance_from_unsubmitted_application_spec.rb:6
 - [x] ./spec/system/candidate_interface/continuous_applications/course_selection/candidate_deletes_application_spec.rb:6
 - [x] ./spec/system/candidate_interface/continuous_applications/withdraws/candidate_withdraws_spec.rb:18
 - [x] ./spec/system/candidate_interface/continuous_applications/course_selection/candidate_edits_course_choices_spec.rb:7

More test that fail 

 - [x] spec/system/candidate_interface/signup_and_signin/candidate_signs_in_and_prefills_application_in_sandbox_spec.rb:6
 - [x] spec/system/candidate_interface/entering_details/candidate_entering_other_qualification_spec.rb:6
 - [x] spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_references_spec.rb:6
 - [x] spec/system/candidate_interface/feedback/candidate_submits_application_with_feedback_form_previously_completed_spec.rb:6
 - [x] spec/system/candidate_interface/references/candidate_views_their_references_on_the_post_offer_dashboard_spec.rb:6
 - [x] spec/system/candidate_interface/offers_and_withdrawals/candidate_can_see_their_rejection_reasons_on_apply_again_spec.rb:4
 - [x] spec/system/candidate_interface/submitting/candidate_submitting_application_spec.rb:6
 - [x] spec/system/candidate_interface/submitting/candidate_submits_application_with_full_course_location_spec.rb:6
 - [x] spec/system/candidate_interface/course_selection/candidate_selecting_a_course_when_only_one_site_available_spec.rb:6
 - [x] spec/system/candidate_interface/entering_details/candidate_entering_disability_info_spec.rb:6
 - [x] spec/system/candidate_interface/signup_and_signin/candidate_signs_up_using_magic_link_with_an_invalid_token_spec.rb:6
 - [x] spec/system/candidate_interface/offers_and_withdrawals/candidate_withdraws_with_upcoming_interviews_spec.rb:6
 - [x] spec/system/candidate_interface/offers_and_withdrawals/candidate_declines_offer_spec.rb:6
 - [x] spec/system/candidate_interface/entering_details/degrees/candidate_delete_and_replace_degrees_spec.rb:6

**More again**

 - [x] ./spec/system/candidate_interface/entering_details/degrees/candidate_delete_and_replace_degrees_spec.rb:6
 - [x] ./spec/system/candidate_interface/entering_details/candidate_entering_subject_knowledge_spec.rb:6
 - [x] ./spec/system/candidate_interface/navigation_tabs_spec.rb:5
 - [x] ./spec/system/candidate_interface/submitting/candidate_submits_application_with_a_missing_address_spec.rb:6
 - [x] ./spec/system/candidate_interface/entering_details/candidate_becoming_a_teacher_spec.rb:6
 - [x] ./spec/system/candidate_interface/course_selection/candidate_selecting_a_course_that_is_full_spec.rb:6
 - [x] ./spec/system/candidate_interface/submitting/candidate_submits_application_with_course_not_yet_available_spec.rb:6
 - [x] ./spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_english_as_foreign_language_section_feature_flag_disabled_spec.rb:7
 - [x] ./spec/system/candidate_interface/course_selection/candidate_selecting_a_course_study_mode_spec.rb:6
 - [x] ./spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_work_experience_section_spec.rb:6
 - [x] ./spec/system/candidate_interface/course_selection/candidate_adds_a_course_theyve_already_chosen_spec.rb:6
 - [x] spec/system/candidate_interface/course_selection/candidate_adds_a_course_theyve_already_chosen_spec.rb
 - [x] spec/system/candidate_interface/signup_and_signin/candidate_signs_in_and_starts_blank_application_spec.rb

**Final set of failures?**

- [ ] rspec ./spec/system/candidate_interface/apply_again/candidate_applies_again_spec.rb:6
- [ ] rspec ./spec/system/candidate_interface/apply_again/candidate_applies_again_updates_personal_statement_spec.rb:6

## Things to check

- [ ] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] If this code adds a column to the DB, decide whether it needs to be in analytics yml file or analytics blocklist
- [ ] API release notes have been updated if necessary
- [ ] If it adds a significant user-facing change, is it documented in the [CHANGELOG](CHANGELOG.md)?
- [ ] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Comment by inulty-dfe** [comment]
**integration_candidate, on**

```
iain ~/Code/dfe/apply-for-teacher-training (fix-find-opens-integration-test-failures $) $ DEFAULT_FEATURE_FLAG_STATE=on TEST_DATE_AND_TIME='2023-10-04 09:00:00' bundle exec rspec ./spec/system/candidate_interface/adviser_sign_up/candidate_signs_up_for_an_adviser_spec.rb:8 ./spec/system/candidate_interface/entering_details/candidate_entering_gcse_science_award_spec.rb:6 ./spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_course_selection_section_spec.rb:7 ./spec/system/candidate_interface/rejection/deleting_a_reason_for_rejection_does_not_impact_the_candidate_interface_spec.rb:4 ./spec/system/candidate_interface/entering_details/candidate_entering_gcse_spec.rb:6 ./spec/system/candidate_interface/feedback/candidate_completes_the_feedback_form_spec.rb:6 ./spec/system/candidate_interface/continuous_applications/withdraws/candidate_withdraws_spec.rb:18 ./spec/system/candidate_interface/entering_details/candidate_viewing_a_science_gcse_spec.rb:6 ./spec/system/candidate_interface/continuous_applications/course_selection/candidate_edits_course_choices_spec.rb:7 ./spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_contact_details_section_spec.rb:6 ./spec/system/candidate_interface/rejection/candidate_reviews_reasons_for_rejection_spec.rb:4 ./spec/system/candidate_interface/course_selection/candidate_does_not_know_where_they_want_to_apply_spec.rb:6 ./spec/system/candidate_interface/course_selection/candidate_sees_add_additional_courses_after_adding_course_spec.rb:7 ./spec/system/candidate_interface/submitting/candidate_reviews_application_and_completes_equality_and_diversity_spec.rb:6 ./spec/system/candidate_interface/signup_and_signin/candidate_email_tracking_spec.rb:6 ./spec/system/candidate_interface/course_selection/candidate_edits_course_choices_spec.rb:7 ./spec/system/candidate_interface/references/candidate_carries_over_unsubmitted_application_spec.rb:6 ./spec/system/candidate_interface/offers_and_withdrawals/candidate_withdraws_spec.rb:18 ./spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_personal_details_section_spec.rb:6 ./spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_adjustments_section_spec.rb:6 ./spec/system/candidate_interface/references/candidate_submits_a_duplicate_application_spec.rb:6 ./spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_unpaid_experience_section_spec.rb:6 ./spec/system/candidate_interface/references/candidate_request_references_spec.rb:6 ./spec/system/candidate_interface/course_selection/sandbox_user_apply_from_find_spec.rb:6 ./spec/system/candidate_interface/entering_details/candidate_completes_contact_details_with_a_missing_address_feature_flag_disabled_spec.rb:6 ./spec/system/candidate_interface/course_selection/candidate_selecting_a_course_spec.rb:6 ./spec/system/candidate_interface/signup_and_signin/candidate_views_guidance_from_unsubmitted_application_spec.rb:6 ./spec/system/candidate_interface/submitting/candidate_reviewing_application_with_unavailable_course_options_spec.rb:6 ./spec/system/candidate_interface/submitting/candidate_submits_application_with_full_course_study_mode_spec.rb:6 ./spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_personal_statement_section_spec.rb:6 ./spec/system/candidate_interface/guidance/public_user_spec.rb:4 ./spec/system/candidate_interface/continuous_applications/course_selection/backlinks_spec.rb:7 ./spec/system/candidate_interface/signup_and_signin/candidate_signs_in_with_the_penultimate_valid_token_spec.rb:6 ./spec/system/candidate_interface/submitting/candidate_submits_application_with_a_removed_site_spec.rb:6 ./spec/system/candidate_interface/continuous_applications/course_selection/candidate_deletes_application_spec.rb:6 ./spec/system/candidate_interface/course_selection/candidate_deletes_course_after_completing_section_spec.rb:6 ./spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_qualifications_spec.rb:6 ./spec/system/candidate_interface/continuous_applications/submitting/redirect_to_your_applications_spec.rb:6 ./spec/system/candidate_interface/continuous_applications/submitting/redirect_to_your_applications_spec.rb:18 ./spec/system/candidate_interface/continuous_applications/submitting/redirect_to_your_applications_spec.rb:12 ./spec/system/candidate_interface/submitting/international_candidate_submitting_application_spec.rb:7 ./spec/system/candidate_interface/entering_details/candidate_entering_english_gcse_spec.rb:6

...

Randomized with seed 22449
ℹ️  If you change CSS, JS, or Assets - don't forget to run `rake compile_assets` before your test runs
ℹ️  Running tests with all features ON by default
...........................................

Finished in 2 minutes 16.4 seconds (files took 9.85 seconds to load)
43 examples, 0 failures

Randomized with seed 22449
```

**Comment by inulty-dfe** [comment]
**integration_candidate, off**

```
iain ~/Code/dfe/apply-for-teacher-training (fix-find-opens-integration-test-failures $) $ DEFAULT_FEATURE_FLAG_STATE=off TEST_DATE_AND_TIME='2023-10-04 09:00:00' bundle exec rspec spec/system/candidate_interface/continuous_applications/course_selection/backlinks_spec.rb:7 spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_personal_statement_section_spec.rb:6 spec/system/candidate_interface/continuous_applications/submitting/redirect_to_your_applications_spec.rb:12 spec/system/candidate_interface/continuous_applications/submitting/redirect_to_your_applications_spec.rb:6 spec/system/candidate_interface/continuous_applications/submitting/redirect_to_your_applications_spec.rb:18 spec/system/candidate_interface/guidance/public_user_spec.rb:4 spec/system/candidate_interface/references/candidate_request_references_spec.rb:6 spec/system/candidate_interface/signup_and_signin/candidate_views_guidance_from_unsubmitted_application_spec.rb:6 spec/system/candidate_interface/continuous_applications/course_selection/candidate_deletes_application_spec.rb:6 spec/system/candidate_interface/continuous_applications/withdraws/candidate_withdraws_spec.rb:18 spec/system/candidate_interface/continuous_applications/course_selection/candidate_edits_course_choices_spec.rb:7

...

Randomized with seed 46533
ℹ️  If you change CSS, JS, or Assets - don't forget to run `rake compile_assets` before your test runs
ℹ️  Running tests with all features OFF by default
............

Finished in 13.08 seconds (files took 9.72 seconds to load)
12 examples, 0 failures

Randomized with seed 46533
```

**Comment by inulty-dfe** [comment]
**integration_shared, on**

```
iain ~/Code/dfe/apply-for-teacher-training (fix-find-opens-integration-test-failures $) $ DEFAULT_FEATURE_FLAG_STATE=on TEST_DATE_AND_TIME='2023-10-04 09:00:00' bundle exec rspec ./spec/system/register_api/register_receives_application_spec.rb:8
^C
iain ~/Code/dfe/apply-for-teacher-training (fix-find-opens-integration-test-failures $) $ $ DEFAULT_FEATURE_FLAG_STATE=off TEST_DATE_AND_TIME='2023-10-04 09:00:00' bundle exec rspec spec/system/register_api/register_receives_application_spec.rb:8 spec/system/inactive_application_spec.rb:6

Randomized with seed 42688
ℹ️  If you change CSS, JS, or Assets - don't forget to run `rake compile_assets` before your test runs
ℹ️  Running tests with all features OFF by default
..

Finished in 6.48 seconds (files took 10.19 seconds to load)
2 examples, 0 failures

Randomized with seed 4268
```

**Review by tomas-stefano — APPROVED** [review]

**Comment by inulty-dfe** [comment]
[CA: Failing future specs - Find opens: integration (multiple)](https://trello.com/c/Wh3IoAPq/587-ca-failing-future-specs-find-opens-integration-multiple)

**Pull request merged**
