### PR TITLE
Remove legacy Languages section

### PR DESCRIPTION
**Pull request by avinhurry**
## Context

The Languages section within personal details has been superceded by the English as a Foreign Language section in Qualifications. We are removing the old section.

## Changes proposed in this pull request

- See commits

## Guidance to review

- Anyone reason why this shouldn't be merged?

## Link to Trello card

https://trello.com/c/H74qRiJi/4661-languages-section-tech-debt

### CODE REVIEW

**Review by JonF1 — APPROVED** [review]
LGTM

Where those fields are set to nil in the application form factory, do we even need them at all as they'll default to nil?

**Review by frankieroberto — APPROVED** [review]
Looks good to me, thanks for doing this.

Is there any impact on Manage and the API? Should we drop the fields from those too?

**Comment by cwrw** [comment]
> Is there any impact on Manage and the API? Should we drop the fields from those too?

I'm looking into the impact of this on both so please hold off merging until we confirm. Also please note we cannot remove API fields or nullify them without notice as that would be a breaking change

**Comment by frankieroberto** [comment]
> > Is there any impact on Manage and the API? Should we drop the fields from those too?
> 
> I'm looking into the impact of this on both so please hold off merging until we confirm. Also please note we cannot remove API fields or nullify them without notice as that would be a breaking change

What do we currently do for the `english_main_language` field in the API?

The [API docs](https://www.apply-for-teacher-training.service.gov.uk/api-docs/v1.1/reference) don’t say that it is optional, but we’ve not asked this question for ages... `english_language_qualifications` and `other_languages` both say they're optional, so presumably are already set as `null` for all candidates who haven't been asked the question?

**Review by cwrw — COMMENTED** [review]
I've done the following analysis on the fields that are populated by this deprecated form:
```
english_main_language
english_language_details
other_language_details
```
In Manage: we render a partial `LanguageSkillsComponent` if the `english_main_language` value is populated in the database, otherwise we hide this section. We don't need to worry about this or remove it as we have data in this cycle/previous cycles where these values are populated

In the Vendor API: we surface those three fields as:
```
english_main_language	
english_language_qualifications
other_languages
```
The `english_main_language` is not optional and always a boolean. We currently have a [work around](https://github.com/DFE-Digital/apply-for-teacher-training/blob/main/app/models/application_form.rb#L351) to always return this value even if not persisted, so we are ok. The others are already optional and can be `nil`, however `english_language_qualifications` is populated from other values past those fields (`english_proficiency`) 

I've checked the data in this cycle and previous cycle and we do have records in this cycle that have this value populated. I think it is safe to remove the legacy forms, however we should keep the `LanguageSkillsComponent` in manage, and not amend the field values in the API as they already account for this deprecation.

**Pull request merged**
