### PR TITLE
Fix link

### PR DESCRIPTION
**Pull request by matt40k**
## Context

To fix broken link

## Changes proposed in this pull request

Fix broke link

## Guidance to review

Click the link

## Link to Trello card

NA

## Things to check

NA

### CODE REVIEW

**Review by duncanjbrown — APPROVED** [review]
Thank you! 🙂

**Comment by duncanjbrown** [comment]
@matt40k hello! Please could you re-raise this PR? We've just re-enabled CI to run on forks, which'll fix the sea of amber ☝️

**Comment by matt40k** [comment]
@duncanjbrown  Sure.

**Comment by matt40k** [comment]
@duncanjbrown much better

**Pull request merged**
