### PR TITLE
ApplicationFeedback cleanup (part2)

### PR DESCRIPTION
**Pull request by davidgisbey**
## Context
**Do not merge until #3806 has been deployed**

PR that removed the need for several bools on the ApplicationFeedback model is #3793

First PR that removed references to the bools is #3806

This PR just drops the bools from the ApplicationFeedback table and adds a feedback column

## Changes proposed in this pull request

Drop the following columns  to the application_feedback table:

- does_not_understand_section
- need_more_information
- answer_does_not_fit_format

Adds the following columns to the application_feedback table:

- feedback 

## Guidance to review

Frankie has gone through the feedback and determined that we don't need to worry about backfilling the records with the dropped bools as candidates have left explanations in the other_feedback column.

## Link to Trello card

https://trello.com/c/UBt82tOr/2843-remove-unneeded-booleans-from-the-applicationfeedback-class

## Things to check

- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by frankieroberto** [comment]
@davidgisbey this PR doesn't seem to include the migration to add the `feedback` column?

**Review by raamSoftwire — COMMENTED** [review]
I can see the old columns have been removed, but did you also intend to add a new `feedback` column?

**Comment by raamSoftwire** [comment]
> I can see the old columns have been removed, but did you also intend to add a new `feedback` column?

Sorry, I only just saw Frankie's comment.

**Comment by davidgisbey** [comment]
Yea sorry good spot hadn't pushed up 🤦 thanks guys

**Review by frankieroberto — APPROVED** [review]

**Pull request merged**
