### PR TITLE
Split up CSS and JS assets

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
## Context

Investigating the consequence of serving the same CSS and JavaScript to all users. May want to choose a different way of splitting up individual files, but this is just a draft to get the raw numbers, and to create a review app can use to test with performance analysis tools.

### CSS

| File | Bytes (Gzipped) | Difference |
|-|-|-|
| application.css (current) | 16,562 ||
| application-candidate.css | 12,953 | -21.8% |
| application-provider.css | 15,011 | -9.4% |
| application-support.css | 12,797 | -22.7% |
| application-api-docs.css | 12,616 | -23.8% |

### JavaScript

| File | Bytes (Gzipped) | Difference |
|-|-|-|
| application.js (current) | 59,234 ||
| application-candidate.js | 22,385 | -62.2% |
| application-provider.js | 46,951 | -20.7% |
| application-support.js | 9,968 | -83.2% |
| application-api-docs.js | 9,971 | -83.2% |

### Comparison

Total size of combined assets (CSS + JavaScript)

* Current single file: 75.8kB
* Candidate specific file: 35.3kB **(53.4% smaller)**
* Provider specific file: 62.0kB (18.2% smaller)

## Things to check

- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] API release notes have been updated if necessary
- [ ] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by tvararu** [comment]
No idea why the review app is failing. 🤔 

Tested a few dozen pages locally vs QA, all looks good visually apart from the performance dashboard.

### Support: tasks page ✅

Screenshot 2020-08-14 at 16 19 37

### Support: performance page 🔴 

Screenshot 2020-08-14 at 16 19 50

### Support: providers page ✅ 

Screenshot 2020-08-14 at 16 20 06

### Support: candidate page ✅

Screenshot 2020-08-14 at 16 20 39

### Candidate: interstitial page ✅ 

Screenshot 2020-08-14 at 16 21 02

### Candidate: application page ✅ 

Screenshot 2020-08-14 at 16 21 07

### Candidate: personal details page ✅ 

Screenshot 2020-08-14 at 16 21 25

### Candidate: review page ✅ 

Screenshot 2020-08-14 at 16 21 32

### Provider: applications page ✅ 

Screenshot 2020-08-14 at 16 23 14

### Provider: application page ✅ 

Screenshot 2020-08-14 at 16 23 28

### Provider: timeline page ✅ 

Screenshot 2020-08-14 at 16 23 35

### Provider: account page ✅ 

Screenshot 2020-08-14 at 16 24 07

### Vendor: API usage page ✅ 

Screenshot 2020-08-14 at 16 25 08

**Comment by tvararu** [comment]
JS also seems to work!

Screenshot 2020-08-14 at 16 39 08

**Comment by paulrobertlloyd** [comment]
@tvararu Fixed performance dashboard styles.

**Comment by duncanjbrown** [comment]
Provider interface looks 👌.

Wasn't sure in the thread but now I see this I really like it. Everything's so explicit. Thank you @paulrobertlloyd! ⭐

**Pull request merged**
