### PR TITLE
[1091] Add AI guidance

### PR DESCRIPTION
**Pull request by avinhurry**
## Context

Adding AI guidance for providers and candidates.

## Changes proposed in this pull request

- Add separate AI guidance for candidates and providers.
- Add respective links to the guidance from the footer.

### Provider Screenshot

image

### Candidate Screenshot

image

## Link to Trello card

https://trello.com/c/hUVlh4ay/1091-publish-2-pages-for-our-ai-guidance-for-candidates-and-providers

## Things to check

- [x] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] If this code adds a column to the DB, decide whether it needs to be in analytics yml file or analytics blocklist
- [x] API release notes have been updated if necessary
- [x] If it adds a significant user-facing change, is it documented in the [CHANGELOG](CHANGELOG.md)?
- [x] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Comment by avinhurry** [comment]
[Publish 2 pages for our AI guidance for candidates and providers](https://trello.com/c/hUVlh4ay/1091-publish-2-pages-for-our-ai-guidance-for-candidates-and-providers)

**Comment by JR-G** [comment]
Happy to consider this out of scope for the card (as is existing behaviour) but good if we could do it!

On the candidate interface we keep the 'Your details' highlighted whilst reviewing the guidance (and the other pages linked from the footer). 

On the provider interface we remove the highlight if one of the footer links are clicked:
image

**Comment by MylesJarvis** [comment]
I have one question that I'd like to ask @RoseMackworth. On the draft text we put, I put a suggestion on using
> inset text
on the provider document where we (re)render the candidate guidance we give. @avinhurry did you get any views on this when creating it?

**Comment by avinhurry** [comment]
> Happy to consider this out of scope for the card (as is existing behaviour) but good if we could do it!
> 
> On the candidate interface we keep the 'Your details' highlighted whilst reviewing the guidance (and the other pages linked from the footer).
> 
> On the provider interface we remove the highlight if one of the footer links are clicked: image

@JR-G what is the intended behaviour be here? It feels like it shouldn't be highlighted because the links in the footer are not related to any of those tabs. 

Let's card it up and make a new PR for it as it's a wider issue.

**Review by MylesJarvis — APPROVED** [review]

**Review by JR-G — APPROVED** [review]

**Pull request merged**
