### PR TITLE
Remove duplicate references from the ApplicationReferences export

### PR DESCRIPTION
**Pull request by davidgisbey**
## Context

At the moment, duplicate references are exposed in the ApplicationReference export. This causes issues with automation of the export analysis purposes as specific columns are used to calculate average response time etc. which is skewed when you have duplicate values.

## Changes proposed in this pull request

- Reject duplicate references from the ApplicationReference export

## Guidance to review

Does this seem reasonable?

There's definitely a trade-off as this is now only showing *new* references which could be slightly misleading if you don't know that is the behaviour.

## Link to Trello card

https://trello.com/c/hXZDSy12/3264-remove-duplicate-references-from-the-applicationreferenceexport

## Things to check

- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] This code does not rely on the addition/removal of Azure config environment variables in the same Pull Request
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training/blob/master/docs/environment-variables.md#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by malcolmbaig** [comment]
I think on the whole this achieves what we need from the export. Regarding this:

> There's definitely a trade-off as this is now only showing new references which could be slightly misleading if you don't know that is the behaviour.

I think we should do either one of these:
- Include the duplicates, but flag them as such via a new column in the export so that they can be filtered out if needs be
- Document their exclusion in the description of this export

**Comment by davidgisbey** [comment]
Yea we had the show they're dupes vs hide them chat and Mike/Milan wanted them removed. You're right it should definitely be misleading so I'll document it now.

**Review by stevehook — APPROVED** [review]
I think this makes sense so long as whoever consumes the report understands that duplicates are excluded. It could be stated in the `description` in `app/models/data_export.rb`. In any case it's now consistent with the way the reference feature metrics work.

**Comment by davidgisbey** [comment]
Yea I must admit that I do have a soft preference for marking them as dupes and filtering. There's also the question of is a feedback provided reference that gets cancelled still a dupe?

Bit of a can of worms though.

**Pull request merged**
