### PR TITLE
Fixes for A11y issues on candidate landing page

### PR DESCRIPTION
**Pull request by stevehook**
## Context

The _qa_ tag is not deemed to have sufficient contrast for accessibility by Axe. Rather than just pick a different colour we've switched to new `govuk-tag` styles for all non-production environments.

## Changes proposed in this pull request

- [x] Workaround issue with aria-hidden/focus no navigation element - see https://github.com/alphagov/govuk-frontend/issues/1340
- [x] Use new environment tag styles to fix A11y issues

Before:

image

After:

image
image
image
image
image

There are a couple of other places where tags appear for Sandbox specific features, e.g.

image

The production interface is unchanged:

image

## Guidance to review

- Does it look OK?
- Is there any more CSS that we can remove?

## Link to Trello card

https://trello.com/c/ALvwnGc6/1844-include-serious-accessibility-issues-in-axe-tests

## Things to check

- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by fofr** [comment]
Are there screenshots of the other environments too?

**Comment by stevehook** [comment]
> Are there screenshots of the other environments too?

@fofr I've added 'after' screenshots for all the other environments.

**Review by tvararu — APPROVED** [review]
:+1:

**Review by paulrobertlloyd — APPROVED** [review]
Love to see some CSS removed! Wondering if the remaining CSS in `_environments.scss` file could be moved into `_header.scss`, but that can be a separate PR if we think that’s a good idea.

**Pull request merged**
