### PR TITLE
Skip SKE length step for RE courses

### PR DESCRIPTION
**Pull request by elliotcm**
Set length to 8 (weeks) and skip to the next step.

## Context

RE courses only have 8 week SKE courses.

### CODE REVIEW

**Comment by elliotcm** [comment]
[⛷️SKE: Create flow for RE courses in SKE](https://trello.com/c/XFPjq1Xu/1192-%E2%9B%B7%EF%B8%8Fske-create-flow-for-re-courses-in-ske)

**Review by carlosmartinez — APPROVED** [review]

**Review by JR-G — APPROVED** [review]

**Review by carlosmartinez — APPROVED** [review]

**Comment by MaeveRoseveare** [comment]
On the 'Check and send offer' page, there is still a 'Change' link that allows you to change the length from 8 weeks. We should remove that link.

Screenshot 2023-02-24 at 11 58 53

**Comment by elliotcm** [comment]
> On the 'Check and send offer' page, there is still a 'Change' link that allows you to change the length from 8 weeks. We should remove that link.
> 
> Screenshot 2023-02-24 at 11 58 53

@MaeveRoseveare Fix deploying now

**Review by MaeveRoseveare — APPROVED** [review]
Fix looks good!

**Comment by MylesJarvis** [comment]
image

The box looks a bit funny to me, appears to have an extra line at the bottom that leads to 2 borders. Do we know why this is? 

Would be good to fix before we ship.

**Comment by JR-G** [comment]
@MylesJarvis border should be fixed now

**Pull request merged**
