### PR TITLE
Add new test data for continuous applications generation

### PR DESCRIPTION
**Pull request by vassyz**
## Context

This commit adds a few new mixes of states that reflect some of the new states that we could see with continuous applications. To make it easier to test the inactive state of an application, I also added a new `inactive` filter.

## Changes proposed in this pull request

I have added the new states, but with the assumption that the `sample_applications_factory` feature will be enabled. Otherwise, the `TestApplications` class will have to be updated as well.

**Generated applications:**

Screenshot 2023-08-21 at 16 53 05

**New filter**

Screenshot 2023-08-21 at 16 53 17

### CODE REVIEW

**Review by tomas-stefano — APPROVED** [review]
Looks good, I think we should enable the sample applications factory feature flag in QA.

**Review by JR-G — APPROVED** [review]
tested locally and it works for me! The only suggestion i have is to double up on the `continuous_application_choices_states` so we have more to play with!
```
      %i[inactive],
      %i[inactive],
      %i[unsubmitted awaiting_provider_decision awaiting_provider_decision rejected offer],
      %i[unsubmitted awaiting_provider_decision awaiting_provider_decision rejected offer],
      %i[unsubmitted awaiting_provider_decision interviewing offer],
      %i[unsubmitted awaiting_provider_decision interviewing offer],
      %i[inactive unsubmitted awaiting_provider_decision withdrawn],
      %i[inactive unsubmitted awaiting_provider_decision withdrawn],
      %i[unsubmitted unsubmitted unsubmitted unsubmitted],
      %i[unsubmitted unsubmitted unsubmitted unsubmitted],
```

**Comment by vassyz** [comment]
@JR-G @tomas-stefano The fix for the `SampleApplicationsFactory` error: https://github.com/DFE-Digital/apply-for-teacher-training/pull/8481/commits/e171224b6d174a8956be098cb5d2aeb61b103819

**Review by tomas-stefano — APPROVED** [review]
Looks good! 🚀

**Pull request merged**
