### PR TITLE
Update wording of ethnicity questions

### PR DESCRIPTION
**Pull request by frankieroberto**
## Context

This updates the wording of the Ethnicity questions to match that in the [Equality information pattern](https://design-system.service.gov.uk/patterns/equality-information/) in the GOV.UK Design System, which is in turn based on the [Ethnicity harmonised standard](https://analysisfunction.civilservice.gov.uk/policy-store/ethnicity-harmonised-standard/) from the Government Analysis Function.

The changes are mostly ordering changes, ie the ordering of the groups in the options lists, and the ordering within the wording (eg "Irish Traveller or Gypsy" becomes "Gypsy or Irish Traveller").

"Another" has also changed to "Any other" and "Another Mixed background" has changed to "Any other mixed or multiple ethnic background".

## Things to check

- [ ] Does this beak anything to do with the existing stored values in the database?

### CODE REVIEW

**Comment by frankieroberto** [comment]
@carlosmartinez @tomas-stefano this isn't critical to get in for the start of the cycle. Will these wording changes cause any issues with existing data?

**Review by tomas-stefano — APPROVED** [review]
LGTM. Can you also test on QA after is merged, please?

**Comment by frankieroberto** [comment]
@tomas-stefano @carlosmartinez this isn't urgent and can get changed after the new cycle has opened. I'm a bit nervous that it'll break things with existing data, as don’t we store ethnicity as strings in the database?

**Comment by carlosmartinez** [comment]
> @carlosmartinez @tomas-stefano this isn't critical to get in for the start of the cycle. Will these wording changes cause any issues with existing data?

thanks @frankieroberto. suggest we label this as do-not-merge for now - worth spending a bit of time investigating possible impact.

**Comment by carlosmartinez** [comment]
> @frankieroberto @carlosmartinez It has been 24 days since last discussion, do we have anything further planned with this PR?

I think best thing is to close this PR and link it in a card in the backlog, as it requires a bit of non-trivial dev work.

**Comment by frankieroberto** [comment]
Yeah I'm happy to close this if we can add a backlog card for it. Presumably the dev work would be to update either write a data migration to update all the old values, or figure out how to denormalise all this somehow?

**Comment by carlosmartinez** [comment]
@frankieroberto have made a [trello card](https://trello.com/c/1kvIGG17/910-update-wording-of-ethnicity-questions) for the dev work. ok to close this PR for the moment?

**Comment by elliotcm** [comment]
@frankieroberto @carlosmartinez Are we keeping this branch around?

**Comment by frankieroberto** [comment]
@elliotcm it can probably be deleted as I think GitHub still keeps a record?

Ideally we'd still do this _at some point_ but it was more complicated than it seemed and isn't a priority.

**Comment by elliotcm** [comment]
Alright I'll leave it around for the mo.

**Pull request closed without merging**
