### PR TITLE
Add rejection reasons for providers

### PR DESCRIPTION
**Pull request by CatalinVoineag**
## Context

We want to better understand why a provider rejects a candidate. Offering the provider more options of rejection will help us.

This commit adds rejection reasons and the email that the candidate will receive, containing these new emails. We won't be adding any advice to the email yet.

## Changes proposed in this pull request
The reasons checked are new, except for `Degree grade does not meet course requirements` which is reworded 

screenshot

Vendor API change: 
New reason code. this reason code can also be used for rejecting via the post `reject-by-code` endpoint. Both get and post endpoints have been tested on local
```
{
    "code": "R10",
    "label": "School placement",
    "default_details": "We are unable to offer you a place because we could not find a suitable placement"
}
```

## Guidance to review

Go on the review app and reject a candidate with the new rejection reasons

## Things to check

- [ ] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] If this code adds a column to the DB, decide whether it needs to be in analytics yml file or analytics blocklist
- [x] API release notes have been updated if necessary
- [ ] If it adds a significant user-facing change, is it documented in the [CHANGELOG](CHANGELOG.md)?
- [ ] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)
- [ ] Inform data insights team due to database changes
- [x] Make sure all information from the Trello card is in here
- [x] Rebased main
- [x] Cleaned commit history
- [x] Tested by running locally
- [x] Add PR link to Trello card

### CODE REVIEW

**Comment by CatalinVoineag** [comment]
https://trello.com/c/MPNZcOl1/22-manage-add-new-rejection-reasons?filter=member:catalinvoineag1

**Review by dcyoung-dev — COMMENTED** [review]
Have we made these new reasons available via the API?

**Comment by CatalinVoineag** [comment]
> Have we made these new reasons available via the API?

Good catch, I've added `School placement` reason code to the vendor API. The vendor can also reject by this new reason code.

**Review by dcyoung-dev — COMMENTED** [review]
I don't know why our API docs don't update or why we are so specific but would you mind adding the `R10` code to the [API Docs](https://www.apply-for-teacher-training.service.gov.uk/api-docs/v1.5/reference#objectlistresponse-object)

**Review by dcyoung-dev — APPROVED** [review]
I'm happy that we've considered everything we know about. It might be worth running this one passed @tomas-stefano as he has also recently added Rejection Reasons 👍

**Pull request merged**
