### PR TITLE
Lint SCSS files according to the GDS style guide

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
## Context

There is currently no linting performed on our CSS. We can use Stylelint and use the [GDS config](https://github.com/alphagov/stylelint-config-gds) to:

* ensure we are following the GDS style guide for (S)CSS 
* alert us of any syntactical errors

It won’t catch everything, but it’ll catch some stuff. We can add further rules later if we feel the need to do so.

(FWIW, GDS [no longer maintain their SCSS-Lint config](https://github.com/alphagov/scss-lint-govuk), so it seemed to make sense to use a node package, rather a Ruby gem in this instance.)

## Changes proposed in this pull request

* Add `stylelint` and `stylelint-config-gds` packages
* Add a new Rake task, `stylelint`. This runs a node package, rather than a Ruby gem.
* Fix the reported errors.

Fun fact, I suspect we’ve been shipping a lot of comments in our deployed CSS; by using `//` instead of `/*`, we should hopefully reduce the size of our CSS, even if only by a tiny amount.

## Guidance to review

* Is this something we want to do?
* Should this be added to CI?
* Any of the fixes look problematic?

## Things to check

- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] API release notes have been updated if necessary
- [ ] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Review by duncanjbrown — COMMENTED** [review]
I'm in favour! what do you think @cwrw and @davidgisbey ?

**Comment by duncanjbrown** [comment]
We could add to CI by adding a step here: https://github.com/DFE-Digital/apply-for-teacher-training/blob/master/.github/workflows/build.yml#L78

**Comment by frankieroberto** [comment]
The GOV.UK Design System team seem to use their stylelint config, which is based on it the GDS one but has some additions: https://github.com/alphagov/govuk-frontend/blob/main/.stylelintrc.yml 🤷

**Comment by paulrobertlloyd** [comment]
> The GOV.UK Design System team seem to use their stylelint config, which is based on it the GDS one but has some additions: https://github.com/alphagov/govuk-frontend/blob/main/.stylelintrc.yml 🤷

Looks like they’re linting for the order of properties… possibly a bit overkill for our needs?

**Comment by frankieroberto** [comment]
@paulrobertlloyd ah yeah, I didn't look long enough to spot that that's the only difference. Definitely overkill for us.

**Comment by cwrw** [comment]
I think this is also a good idea and doesn't add too much to the build running time (around 2 sec). 
Could we remove the `package-lock.json` from being in the commit, as everything is in the `yarn.lock`? 

Only other note is that this added a very large number of new dependencies.

**Comment by paulrobertlloyd** [comment]
> Could we remove the `package-lock.json` from being in the commit, as everything is in the `yarn.lock`?

Oops, fixed!

> Only other note is that this added a very large number of new dependencies.

Only adds 2 direct dependancies: `stylelint` and `stylelint-config-gds` (what they depend on is probably quite large; welcome to the wild world of Node 🙄)

**Comment by paulrobertlloyd** [comment]
Unsure why, but the linting task doesn’t run from the GitHub workflow, even though it works locally:

```
▸ Run bundle exec rake stylelint
yarn stylelint app/frontend/styles
rake aborted!
Command failed with status (127): [yarn stylelint app/frontend/styles...]
```

🤔

**Comment by duncanjbrown** [comment]
> Unsure why, but the linting task doesn’t run from the GitHub workflow, even though it works locally:
> 
> ```
> ▸ Run bundle exec rake stylelint
> yarn stylelint app/frontend/styles
> rake aborted!
> Command failed with status (127): [yarn stylelint app/frontend/styles...]
> ```
> 
> 🤔

I think this is because the yarn deps are only installed at build time — I think we'll have to run stylelint then. Attempting.

**Review by duncanjbrown — APPROVED** [review]

**Pull request merged**
