### PR TITLE
Update content on content providers view

### PR DESCRIPTION
**Pull request by george-bit**
## Context

Editing down text on training providers available through apply for teacher training page.

## Changes proposed in this pull request
Before:
image

After:
image

## Guidance to review

review against the design spec in the trello card https://docs.google.com/document/d/1nCmK-sAfMNPDzjdDNA0119qRtL3DysEBOFL9e5bmjvk/edit#

## Link to Trello card

https://trello.com/c/hB66Shmz/1839-dev-content-changes-on-training-providers-available-through-apply-for-teacher-training-page

## Things to check

- [x] This code doesn't rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by george-bit** [comment]
The title has now changed on this page as a result. I wonder whether the nomenclature in en.yml and for the view itself should change to reflect this?

**Comment by EmmaFrith** [comment]
Thanks @george-bit 

Am I alright to change the content slightly? (My bad)

Have updated the content on the google doc here: https://docs.google.com/document/d/1nCmK-sAfMNPDzjdDNA0119qRtL3DysEBOFL9e5bmjvk/edit?usp=sharing

I've changed:

- the text included in the Apply for teacher training hyperlink (so that it's consistent with the UCAS hyperlink)
- added a sentence re-iterating that candidates can only apply for 3 courses in total, as a provider complained that this message wasn't getting across

**Comment by george-bit** [comment]
Thanks @EmmaFrith 

I have made the suggested changes, please review.

**Comment by EmmaFrith** [comment]
awesome looks brill! thanks @george-bit :)

**Pull request merged**
