### PR TITLE
Add details component

### PR DESCRIPTION
**Pull request by AgaDufrat**
## Context

We use `<details>` HTML tag multiple time in all interfaces. It should be a component
## Changes proposed in this pull request

See commits for details. No visual change.

## Link to Trello card

https://trello.com/c/Ci0WZjb2/353-low-add-details-component

## Things to check

- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] API release notes have been updated if necessary
- [ ] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by AgaDufrat** [comment]
I forgot `dfe-digital/govuk-components` exist 🙈  I will try to use that instead

**Comment by peteryates** [comment]
Hey I just noticed this. The components both look pretty similar, the main difference is that the `GovukComponent` variant accepts the details as a string **or** block.

The jump would be something like changing this:

```erb

<% details_body = capture do %>
    <h1>Hello!</h1>
<% end %>

<%= render DetailsComponent.new(
    summary_text: "What to do if you’re unable to start training in 3 weeks",
    details_body: details_body,
    additional_css_classes: 'govuk-!-margin-bottom-0 govuk-!-margin-top-2',
) %>
```

To this:

```erb

<%= render GovukComponent::Details.new(
    summary: "What to do if you’re unable to start training in 3 weeks",
    classes: 'govuk-!-margin-bottom-0 govuk-!-margin-top-2') do %>
    <h1>Hello!</h1>
<% end %>
```

If you need to extend or modify the component to better fit your needs, PRs are more than welcome or give me a shout.

**Comment by AgaDufrat** [comment]
⏯️ Paused to sort out UCAS matches. I will go with @peteryates approach (I think the order of text is better).

**Comment by duncanjbrown** [comment]
@AgaDufrat would you like to close this PR but keep the branch, then re-raise once it's ready for review?

**Pull request closed without merging**
