### PR TITLE
Update content on EAFL view and locale

### PR DESCRIPTION
**Pull request by george-bit**
## Context

Making these tweaks to content based on feed back from previous PR: https://github.com/DFE-Digital/apply-for-teacher-training/pull/2941

## Changes proposed in this pull request

Please view in review app.

## Guidance to review

Please review content changes in files changed and in the review app.

## Link to Trello card

https://trello.com/c/Up35mAyz/2142-%F0%9F%8C%90-dev-and-content-change-all-refs-to-english-as-a-foreign-language-qualification-to-assessment-candidate-ui

## Things to check

- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Review by paulrobertlloyd — APPROVED** [review]

**Comment by george-bit** [comment]
Hey @EmmaFrith, Do you want to cast your brilliant content eye over this before it's merged?

**Comment by EmmaFrith** [comment]
hey @george-bit thanks - I tried clicking on 'view deployment' but I can't see the changes - when adding support to the URL it says page not found. 

i've also made comments in this slack thread: https://ukgovernmentdfe.slack.com/archives/CP18YJXPY/p1600696283075800 - but I'm not sure if that covers the work in this pull request. 

Maybe easier to chat tomorrow?

**Comment by EmmaFrith** [comment]
hey @george-bit, this looks great! 

i've spotted one more thing, sorry!

on the review pages, we've got 'Year awarded' as a heading - could you change this to 'Year completed'?

also, on one of the error messages (the one in the TOEFL section) we've got 'Enter a number' as an error message. this doesn't seem very accessible to me, would u agree @paulrobertlloyd? should it be something more like, 'Enter a score (this should be a number)'

**Comment by paulrobertlloyd** [comment]
> also, on one of the error messages (the one in the TOEFL section) we've got 'Enter a number' as an error message. this doesn't seem very accessible to me, would u agree @paulrobertlloyd? should it be something more like, 'Enter a score (this should be a number)'

Assuming this message is when answer is blank, we should say:

`Enter your band score`

I don’t think we’re validating if this is the right format yet, but if we are, we should say:

`Enter your band score in the correct format, like 7.5`

That sound good @EmmaFrith?

**Review by EmmaFrith — APPROVED** [review]
Looks great pending that one final change about the error message on the TOEFL page. Thanks @george-bit !

**Pull request merged**
