### PR TITLE
User permissions tweaks

### PR DESCRIPTION
**Pull request by steventux**
## Context

We'd like to make the process of onboarding provider users and managing their permissions much easier to understand.

## Changes proposed in this pull request

- Amend layout of edit user permissions form to nest existing permissions form elements inside radio group (see screenshot)
- Amend layout of setup user permissions form to nest existing permissions form elements inside radio group (see screenshot)
- Amend copy on the 'check' step when inviting a new provider user.

### Validating top-level permissions option is chosen
image

### Set permissions on setting up a new user
image

### Check permissions on setting up a new user
image

### Edit permissions
image

## Guidance to review

The complexity in this PR is added in nesting the existing permissions form elements inside a radio button group.
This top level set of choices has to be validated when setting up a user and has an effect on the permissions saved against the user (selecting 'view applications only' should remove any previously set/selected permissions).

## Link to Trello card

https://trello.com/c/9idMIMCB/2898-user-permissions-tweaks

## Things to check

- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by adamsilver** [comment]
Awesome work dude.

Anywhere it says ‘Manage organisations’ it should say ‘Manage organisational permissions’

**Comment by adamsilver** [comment]
What does the check screen look like when the user who is doing the inviting belongs to multiple orgs?

And what does the page with nested permissions show when the user doesn't select an option at the top level and child level?

**Comment by steventux** [comment]
@adamsilver I've amended 'Manage organisations' labels here https://github.com/DFE-Digital/apply-for-teacher-training/pull/3271/commits/4424863ce7ff755914528f31d3b7583fbe15334a

I've also added more screenshots of the scenarios you mention, any thoughts on the validation error message? I struggle with words.

**Review by AgaDufrat — APPROVED** [review]
Tested locally and all looking good. 

Not for this PR but we should probably also show the "Does not apply to courses run" section in the organisations permission flow. (`app/components/provider_interface/provider_relationship_permissions_list_component.html.erb`)

**Comment by steventux** [comment]
Thanks @AgaDufrat for spotting the missing cross icons on other permissions component, will make a new PR.

**Review by benswannack — APPROVED** [review]

**Review by adamsilver — APPROVED** [review]

**Pull request merged**
