### PR TITLE
Add Roadmap to Apply for Providers

### PR DESCRIPTION
**Pull request by george-bit**
## Context

Providers need to be aware of our public roadmap. 

## Changes proposed in this pull request

This PR adds it via a markdown file to the provider interface. For the time being I've added
navigation via the spport links.

## Guidance to review

image
image

## Link to Trello card

https://trello.com/c/noIJBZYM/3437-publish-the-apply-public-roadmap

## Things to check

- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] This code does not rely on the addition/removal of Azure config environment variables in the same Pull Request
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training/blob/master/docs/environment-variables.md#azure-hosting-devops-pipeline)

### CODE REVIEW

**Review by paulrobertlloyd — CHANGES_REQUESTED** [review]
This page needs *significant* content design love. I have [recommended some changes and suggested some tweaks to the structure of this page](https://docs.google.com/document/d/1lGsbfc3Q4SHHRjdDBKxjJ7dgM-hNQDU-VNmp7NQrBOs/edit) to make it easier to read and understand.

**Comment by davidgisbey** [comment]
@duncanjbrown how time sensitive in this?

**Comment by duncanjbrown** [comment]
> @duncanjbrown how time sensitive in this?

Not a matter of life and death, but it would be good to get it out this week

**Comment by george-bit** [comment]
Thanks all, let's wait for Gaby's 👍

**Comment by george-bit** [comment]
@duncanjbrown @davidgisbey just waiting on some last min content and design tweaks

**Comment by frankieroberto** [comment]
Could/should we have the URL be `/roadmap` rather than `/provider/roadmap`, as it applies to the whole service and not just providers?

**Comment by paulrobertlloyd** [comment]
> Could/should we have the URL be `/roadmap` rather than `/provider/roadmap`

If/when different parts of this monolith are served from different domains (one can dream…), which would it sit under? The answer to that hypothetical is why I think `/provider/roadmap` is probably the right choice.

**Comment by frankieroberto** [comment]
@paulrobertlloyd:
> If/when different parts of this monolith are served from their own domains (one can dream…), which would it sit under? The answer to that hypothetical is why I think /provider/roadmap is probably the right choice.

Good point. I guess this content is mainly aimed at providers too?

**Comment by george-bit** [comment]
Just had a chat with @duncanjbrown, this is a provider facing feature so `/provider/roadmap` should be okay can always review later if needs be.

**Pull request merged**
