### PR TITLE
Add back links to Accessibility, Cookies, Privacy policy, Terms of use and Complaints

### PR DESCRIPTION
**Pull request by avinhurry**
## Context

Adding back links to the pages in `Changes proposed in this pull request`. In order to add dynamic back links to these pages, they needed to be converted to `html.erb` files first.

## Changes proposed in this pull request

- Convert the following markdown pages into HTML pages: 

- `Make a complaint or give feedback` 
- `Accessibility` 
- `Cookies`
- `Privacy policy`
- `Terms of use`

- Add back links to these pages 
- These changes also apply to provendor (except `terms of use` and `Privacy policy`)

## Guidance to review

- This change means we will have two seperate privacy notices. Provendor uses the `ContentHelper` to generate breadcrumbs on this page (as they have two privacy policies). This is also in the same place that the back links would be. Any thoughts are welcome! 

- Look for typos, duplicated content etc

## Link to Trello card

https://trello.com/c/WUyAMccc/4428-design-guidance-pages-dont-have-links-back-to-application-task-list

### CODE REVIEW

**Comment by EmmaFrith** [comment]
Thanks @avinhurry! I think this looks great.

**Review by EmmaFrith — APPROVED** [review]

**Comment by frankieroberto** [comment]
I'm not sure this is particularly necessary? Because these static pages are linked to from _every_ page (in the footer), the back link could take you anywhere, which feels a bit weird.

Relying the referer header also means you can get stuck in loops, where if you, say visit the terms of use page after the privacy policy page, and then keep pressing the back links, you end up alternating between the two pages. Also if you click on the page in the footer that you're already on, so that it reloads again, the back link ends up linking to the page you're already on. Finally if you land on one of the static pages from an external link, there's a back link to the main candidate sign in page – which is probably ok, but maybe a bit confusing as it isn't really taking you back to where you were previously?

That said, maybe this is all fine, and at least helps users who might read the terms of use from the sign up flow (which I imagine is very few people, but still..).

**Comment by EmmaFrith** [comment]
I didn't think about this issue until I visited these pages and then didn't know how to go back to the task list. 

If you're on a website on a desktop computer you don't always think to use your back button on your browser, because it's quite far away from the action. 

Screenshot 2022-03-04 at 10 32 10

**Comment by frankieroberto** [comment]
@EmmaFrith I like the idea of a "Back to application" link, as that tells you where you're going, and doesn't rely on you having been there immediately before (eg would still take you to application if you click on Terms of use and then Privacy policy).

Perhaps we could hardcode this link for all signed-in users, and for signed-out users either have no link or "Home" or "Back to create an account or sign in"?

**Comment by EmmaFrith** [comment]
that sounds good to me @frankieroberto, if there's a better way to solve the problem, do it!

**Comment by avinhurry** [comment]
> @EmmaFrith I like the idea of a "Back to application" link, as that tells you where you're going, and doesn't rely on you having been there immediately before (eg would still take you to application if you click on Terms of use and then Privacy policy).
> 
> Perhaps we could hardcode this link for all signed-in users, and for signed-out users either have no link or "Home" or "Back to create an account or sign in"?

What would home be @frankieroberto? Assume `root_path`

Bare in mind that some of these pages will affect provendor too, so the solution needs to work with them too. Or we have seperate pages for all of these, which i'm not sure about because it means we have to keep both pages up to date. 

The current solution works for both teams.

**Pull request merged**
