### PR TITLE
Remove to work details when a candidate selects they are British or Irish

### PR DESCRIPTION
**Pull request by davidgisbey**
## Context

There is a bug that can be reproduced with the following steps on QA:

1. Complete the personal details section as an Albanian candidate
2. Edit nationality to British and Albanian
3. See the right to work row is there when it should not be

## Changes proposed in this pull request

- Reset the right_to_work_or_study and  right_to_work_or_study_details fields to nil when a candidate selects British or Irish as one of their nationalities
- Update the logic for rendering the right_to_work row to check for Britsh/Irish in all nationalities

## Guidance to review

Previously the logic for whether to render the right to work row only checked the first nationality. The nationalities are stored alphabetically so if someone has picked Austrian/Albanian etc. and British as nationalities it renders the row when it shouldn't.

## Link to Trello card

https://trello.com/c/V6N7Dv0K/2050-%F0%9F%8C%90-dont-show-or-save-residency-status-if-nationality-is-british-or-irish

## Things to check

- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by paulrobertlloyd** [comment]
It’s possibly a bit simpler than this fix implies. If a candidate has either British or Irish nationality, don’t show (or save) any previous answer for residency status.

So, for example, in both the following examples, my previous answer for ‘Residency status’ should not be shown.

Screenshot 2020-09-22 at 18 23 51


Screenshot 2020-09-22 at 18 23 39

**Comment by davidgisbey** [comment]
Cool. I think we should probably also set the values for the right to work response to nil on the application form though. They are no longer relavant and it could be potentially misleading if for example someone queries for all application forms in which those attributes are not blank.

**Comment by paulrobertlloyd** [comment]
> Cool. I think we should probably also set the values for the right to work response to nil on the application form though. They are no longer relavant and it could be potentially misleading if for example someone queries for all application forms in which those attributes are not blank.

Yup. If British or Irish, don’t show or save anything regarding residency status, and remove it if previously added.

**Comment by davidgisbey** [comment]
Perfect. This is good to go once a dev approves then 👍

**Comment by paulrobertlloyd** [comment]
Lovely stuff.

**Review by tvararu — APPROVED** [review]

**Pull request merged**
