### PR TITLE
Fix errors that mobile users are experiencing on apply

### PR DESCRIPTION
**Pull request by tomas-stefano**
## Context

According to the logs we had hundreds errors that users are encountering.

The issue arises because mobile Safari reloads pages from cache after the browser is closed and reopened.

 When this happens, the session cookie that stores the CSRF token is gone, but the form still contains the old token. This mismatch leads to an error when the user tries to submit the form.

Rails stores the authenticity token in a session cookie, which gets deleted when the browser is closed. On mobile Safari, when you reopen the browser, it reloads tabs from cache, but the session cookie is gone. As a result, the authenticity token in the form can't be verified when the form is submitted.

## Solution

* Add the user agent on the logs to help to understand the issue faster (it took me 3 days to understand the issue!)
* Add custom headers

Instruct Safari (and other browsers) to request a fresh version of the page before resubmitting it

1. no-store: Prevents the response from being cached by the browser, ensuring it is fetched anew with every request.
2. no-cache: Requires caches to validate the resource before using it, ensuring that any changes are accounted for before serving the cached version.

### CODE REVIEW

**Comment by tomas-stefano** [comment]
[Fix errors that mobile users are experiencing on Apply](https://trello.com/c/O28XYONO/2198-fix-errors-that-mobile-users-are-experiencing-on-apply)

**Comment by tomas-stefano** [comment]
The assets cache control are left untouched (expected) and the new cache control added:

Screenshot 2024-08-16 at 16 36 20
Screenshot 2024-08-16 at 16 36 39

**Comment by tomas-stefano** [comment]
I recommend who review this PR to test in a mobile as well before approving.

**Comment by dcyoung-dev** [comment]
I stumbled across this [article](https://blog.appsignal.com/2024/08/14/an-introduction-to-http-caching-in-ruby-on-rails.html#implementation-in-rails) on caching today and it got me thinking that we could set a `max-age` on the cache to slightly shorter than a CSRF token is valid for 🤔

**Review by avinhurry — APPROVED** [review]
Tested this on mobile and it worked 🎉

**Comment by tomas-stefano** [comment]
> I stumbled across this [article](https://blog.appsignal.com/2024/08/14/an-introduction-to-http-caching-in-ruby-on-rails.html#implementation-in-rails) on caching today and it got me thinking that we could set a `max-age` on the cache to slightly shorter than a CSRF token is valid for 🤔

Yes, that would be a good to experiment definetely. This will give flexibility as a whole. Future work or card?

**Pull request merged**
