### PR TITLE
Use provider application patterns on support application page

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
## Context

Use provider application review components to display work history and volunteering items in support and generally tidy up the relationship between these two similar pages and their respective components.

## Changes proposed in this pull request

* Moves headings for application review components into these components (DRYer)
* Adjusts size of headings in these components from large to 27px (partly addressing [this change](https://bat-design-history.netlify.app/manage-teacher-training-applications/smaller-headings/))
* Remove application related rows from personal details review component
* Add a provider-facing application summary component
* Include recruitment cycle information in this new application summary (matching prototype)
* Update name spacing for work history and volunteering components:
  * `ProviderInterface::WorkHistoryComponent` → `WorkHistoryComponent` 
  * `ProviderInterface::VolunteeringHistoryComponent` → `VolunteeringHistoryComponent`
  * `ProviderInterface::WorkHistoryItemComponent` → `WorkHistoryItemComponent `
  * `WorkHistoryReviewComponent` → `CandidateInterface::WorkHistoryReviewComponent`
  * `VolunteeringReviewComponent` → `CandidateInterface::VolunteeringReviewComponent`
* Add context regarding cycle year (apply again or carried over) to application summary in support)

| Before | After |
| - | - |
| support-application-old | support-application-new |
| provider-application-old | provider-application-new |

## Link to Trello card

https://trello.com/c/qfGonFDe

## Things to check

- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] API release notes have been updated if necessary
- [ ] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Review by tijmenb — COMMENTED** [review]
Let's have a quick chat about this offline. I think we want to move away from sharing these components between provider/support, because we had a couple of near-misses where we shared data with providers that we didn't want to.

**Comment by tvararu** [comment]
Shall we close this?

**Comment by paulrobertlloyd** [comment]
@tvararu @tijmenb I have started splitting the components up, but is starting to feel a bit icky as lots of duplicated code, and some components (such as qualifications) are nested, which adds further duplication.

Happy to continue that effort in a separate PR, but feels out of scope for what I was trying to achieve here.

**Review by adamsilver — APPROVED** [review]

**Review by tijmenb — APPROVED** [review]

**Comment by paulrobertlloyd** [comment]
🎉

**Pull request merged**
