### PR TITLE
Fix bug on SatisfactionSurveyFeatureMetrics

### PR DESCRIPTION
**Pull request by george-bit**
## Context
It was noticed that the info on the Feature Metrics Dashboard for Satisfaction Survey
did not represent stats. 

## Changes proposed in this pull request

This PR corrects the scope of the query to only look for the
presence of feedback_atisfaction_level for unique candidates.

## Guidance to review

check the scope of the query makes sense.

## Things to check

- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Comment by frankieroberto** [comment]
Personally, I think we should count applications, not distinct users (or choices), as users are presented with the survey after each application submission (eg Apply1 and any Apply2 applications), and we're care about the overall response rate each time they see the survey.

As it stands the maths is a bit off, as it's counting unique users who gave a score by unique users who gave a score + unique users who didn't give a score. So that means that if you gave a score on 2 applications but not on a third one, it'd score as 50% ( 1 / (1 + 1)).

**Comment by stevehook** [comment]
> Personally, I think we should count applications, not distinct users (or choices), as users are presented with the survey after each application submission (eg Apply1 and any Apply2 applications), and we're care about the overall response rate each time they see the survey.
> 
> As it stands the maths is a bit off, as it's counting unique users who gave a score by unique users who gave a score + unique users who didn't give a score. So that means that if you gave a score on 2 applications but not on a third one, it'd score as 50% ( 1 / (1 + 1)).

Yes that's true, as it stands if a candidate gave feedback on one or more applications and not on one or more other applications in the same period they'd be counted as both giving _and_ not giving feedback. I think the way to solve this is to count candidates that gave feedback and subtract that from the count of all candidates.

When you are looking at numbers for a given month it gets a bit messy because you may have a candidate submit an application in that month _without feedback_, after having submitted another application _with feedback_ in an earlier month. Not sure how you solve that or whether we really need to worry about it.

**Comment by frankieroberto** [comment]
> When you are looking at numbers for a given month it gets a bit messy because you may have a candidate submit an application in that month without feedback, after having submitted another application with feedback in an earlier month. Not sure how you solve that or whether we really need to worry about it.

I think this is a good reason to count applications submitted rather than users? Probably makes a fairly negligible difference though. 🤷‍♂️

**Comment by stevehook** [comment]
> > When you are looking at numbers for a given month it gets a bit messy because you may have a candidate submit an application in that month without feedback, after having submitted another application with feedback in an earlier month. Not sure how you solve that or whether we really need to worry about it.
> 
> I think this is a good reason to count applications submitted rather than users? Probably makes a fairly negligible difference though. 🤷‍♂️

I agree it makes sense to stick with counting applications. The most important thing right now is to count all the applications/candidates that selected a `feedback_satisfaction_level`. Debating the other stuff can wait.

**Review by stevehook — APPROVED** [review]
Looks good to me. I think the numbers will make much more sense with this change.

Only think I would consider adding is to change the spec so that it sets up applications with just the `feedback_satisfaction_level` populated with `feedback_suggestions` left as `null`. https://github.com/DFE-Digital/apply-for-teacher-training/blob/master/spec/models/satisfaction_survey_feature_metrics_spec.rb#L11

**Pull request merged**
