### PR TITLE
Modification of content on the becoming_a_teacher edit view

### PR DESCRIPTION
**Pull request by george-bit**
## Context

Change to content on the Why do you want to become a teacher page.

## Changes proposed in this pull request
Before:
image
After:
image

## Guidance to review

Check that it fulfils the design brief.

## Link to Trello card

https://trello.com/c/LitfW8u4/1842-dev-content-changes-on-why-do-you-want-to-be-a-teacher-page

## Things to check

- [x] This code doesn't rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by EmmaFrith** [comment]
Thanks @george-bit - looks good!

**Comment by EmmaFrith** [comment]
Could I just made one change to the content actually @george-bit?

Could you change 'You could talk about:' to 'You can include:'

**Comment by george-bit** [comment]
@tijmenb & @tvararu - Title changed and ready to merge.

@EmmaFrith - content updated as per your comment above

**Comment by EmmaFrith** [comment]
thanks @george-bit !

**Pull request merged**
