### PR TITLE
Use different count methods depending on type of relation for batch delivery

### PR DESCRIPTION
**Pull request by elceebee**
## Context

We switched to 'length' rather than 'count' because 'count' does not give us the anticipated response for collections that have been grouped. This will have a very serious impact on performance when we are sending many thousands of emails.

## Changes proposed in this pull request

This PR addresses the problem by using a different count_method depending on whether the collection you are passing to BatchDelivery is grouped or not grouped. 

## Link to Trello card

https://trello.com/c/yVWA4TlR

## Things to check

- [ ] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] If this code adds a column to the DB, decide whether it needs to be in analytics yml file or analytics blocklist
- [ ] API release notes have been updated if necessary
- [ ] If it adds a significant user-facing change, is it documented in the [CHANGELOG](CHANGELOG.md)?
- [ ] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Comment by elceebee** [comment]
[Fix big Performance issue for End of cycle tasks](https://trello.com/c/yVWA4TlR/1640-fix-big-performance-issue-for-end-of-cycle-tasks)

**Review by tomas-stefano — COMMENTED** [review]
Can we have the count being the default of batch delivery and only have the grouped batch delivery added and change in the two places that uses? 
Not a blocker though but I'd like to discuss before approving.

**Comment by elceebee** [comment]
> Can we have the count being the default of batch delivery and only have the grouped batch delivery added and change in the two places that uses? Not a blocker though but I'd like to discuss before approving.

In general, I think it is best to be as explicit as possible, so to me it seems better to make sure the developer knows they need to be deliberate about what BatchDelivery class to use. With a default, it would be less clear to me. But functionally it is the same so if you feel strongly about it, I will change it.

**Comment by elceebee** [comment]
[Fix big Performance issue for End of cycle tasks](https://trello.com/c/yVWA4TlR/1640-fix-big-performance-issue-for-end-of-cycle-tasks)

**Pull request merged**
