### PR TITLE
[429] Set up docker buildx

### PR DESCRIPTION
**Pull request by saliceti**
## Context
Slow build time as docker images are not cached

## Changes proposed in this pull request
Set up docker buildx to keep layers inline so they are cached for next build

## Guidance to review
Same config as other repos

## Link to Trello card
https://trello.com/c/q3vZmV4z

## Things to check

- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] API release notes have been updated if necessary
- [ ] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Comment by saliceti** [comment]
[Improve build time by optimising docker caching](https://trello.com/c/q3vZmV4z/429-improve-build-time-by-optimising-docker-caching)

**Review by cwrw — APPROVED** [review]
I thought we were cahing?

**Comment by saliceti** [comment]
> I thought we were cahing?

I've noticed the caching is not working at the moment. Everything looks right in the workflow except it's missing the required buildx setup.

**Comment by cwrw** [comment]
hmm this is taking 25 minutes and counting?

**Pull request merged**
