### PR TITLE
Backport External report fixes to the Ministerial report

### PR DESCRIPTION
**Pull request by duncanjbrown**
## Context

Now that we've made the External report spick and span, the Ministerial report is inconsistent.

This PR brings them into line by

- making the specs look at the same data set
- expanding that data set to cover more edge cases that the Ministerial report needs to consider
- ensuring that everything continues to work consistently across all the reports with the same data

## Changes proposed in this pull request

0. The first commit removes a lot of unused code.
0. The following commit ports the Ministerial report tests to use the same dataset as the Monthly report specs, and gets them all to pass against the same data
0. By comparison with the absolute numbers coming out of the external report, we then fix bad behaviour in the Ministerial report
0. Two commits at the end clean up the Ministerial report and spec tooling

The salient changes to behaviour are:

- when we count subjects (in either report) we now consistently bucket FE courses under "Secondary" (following advice from Policy)
- the Ministerial report will include deferred apps, as the External report does
- the Ministerial report will exclude candidates marked to `hide_in_reporting`

Now that everything's consistent and under test, it should be possible to share more code between these reports. I haven't done that here because the PR is already 🐘 🐘 🐘 .

## Guidance to review

It's big — sorry!  Commits should do 🤞 .

## Link to Trello card

https://trello.com/c/mpp02RdH/4185-epic-make-monthly-report-production-ready

## Things to check

- [X] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [X] This code does not rely on migrations in the same Pull Request
- [X] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [X] API release notes have been updated if necessary
- [X] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Review by tomas-stefano — APPROVED** [review]
🚀

**Review by stevehook — APPROVED** [review]
This all makes sense to me. I tested locally and the two ministerial reports ran and the totals checked out (though I didn't check all the numbers).

**Review by JR-G — APPROVED** [review]
Have tested on the review app, all works 👍

**Comment by duncanjbrown** [comment]
Thanks for reviews all!

**Pull request merged**
