### PR TITLE
Add scenario that syncs TDA courses to the teacher training API

### PR DESCRIPTION
**Pull request by tomas-stefano**
## Context

We will need to add tests and guarantees that Apply will sync undergraduate courses, so good to add specs and create a review app that syncs some TDA courses (I need to create some in Publish QA).

### CODE REVIEW

**Comment by tomas-stefano** [comment]
While testing I found some issues on the Publish API:

1. The required_qualification attribute is wrong for TDA courses - it should be nil:

```
"required_qualifications": "Grade 4 (C) or above in English and maths, or equivalent qualification.\nWe will not consider candidates with pending GCSEs.\nWe do not accept equivalency tests.\n\nAn undergraduate degree, or equivalent.",
```

2. Course length is null:

```json
 "course_length": null,
```

**This is not related to this PR but I need to investigate on Publish**

**Comment by tomas-stefano** [comment]
[TDA: Make sure Apply will sync undergraduate courses from Publish](https://trello.com/c/5UUJBk2U/2205-tda-make-sure-apply-will-sync-undergraduate-courses-from-publish)

**Comment by tomas-stefano** [comment]
I will create some TDA courses in QA next week and sync on this review app. I will let you know when that happens.

**Comment by tomas-stefano** [comment]
I created (today as tomorrow this coulrse will be deleted):

https://qa.publish-teacher-training-courses.service.gov.uk//api/public/v1/recruitment_cycles/2025/providers/4A3/courses/D879

I also run the sync in the review app.

```
TeacherTrainingPublicAPI::SyncAllProvidersAndCourses.call(recruitment_cycle_year: 202
5, incremental_sync: false)
```

And the course was created:

```
irb(main):006> Course.teacher_degree_apprenticeship.count
=> 1
```

```
{"id"=>540,
 "provider_id"=>70,
 "name"=>"Art and design",
 "code"=>"D879",
 "created_at"=>Tue, 27 Aug 2024 16:03:33.824062000 BST +01:00,
 "updated_at"=>Tue, 27 Aug 2024 16:03:33.824062000 BST +01:00,
 "level"=>"secondary",
 "exposed_in_find"=>true,
 "recruitment_cycle_year"=>2025,
 "study_mode"=>"full_time",
 "financial_support"=>nil,
 "start_date"=>Mon, 01 Jun 2026 00:00:00.000000000 BST +01:00,
 "course_length"=>"4 years",
 "description"=>"Teacher degree apprenticeship with QTS",
 "accredited_provider_id"=>635,
 "funding_type"=>"apprenticeship",
 "age_range"=>"14 to 19",
 "qualifications"=>["qts", "undergraduate_degree"],
 "program_type"=>"teacher_degree_apprenticeship",
 "withdrawn"=>false,
 "uuid"=>"277f8353-6f4a-4c0a-9a55-a7e8db012f0e",
 "degree_grade"=>"not_required",
"degree_subject_requirements"=>nil,
 "accept_pending_gcse"=>false,
 "accept_gcse_equivalency"=>false,
 "accept_english_gcse_equivalency"=>false,
 "accept_maths_gcse_equivalency"=>false,
 "accept_science_gcse_equivalency"=>false,
 "additional_gcse_equivalencies"=>nil,
 "applications_open_from"=>Tue, 08 Oct 2024 00:00:00.000000000 BST +01:00,
 "fee_details"=>nil,
 "fee_international"=>nil,
 "fee_domestic"=>nil,
 "salary_details"=>"Some info about salary",
 "can_sponsor_skilled_worker_visa"=>false,
 "can_sponsor_student_visa"=>false,
 "application_status"=>"open"}
```

**Review by CatalinVoineag — APPROVED** [review]

**Pull request merged**
