### PR TITLE
Update navigation link styles

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
## Context

This PR updates the styles for primary and tab navigation components (which largely share the same design) so that:

* Closely follows the design of the equivalent navigation styles on the design system website
* Ensures that focus styles are consistent with those for links elsewhere
* Ensures links for non-current navigation items get underlined on hover
* Increases the tap area and space between items
* Fixes the alignment of tab navigation items on mobile
* Ensures the CSS rules are broadly similar across both components

## Changes proposed in this pull request

| Before | After |
| - | - |
| Screenshot 2021-06-28 at 18 08 16 | Screenshot 2021-06-28 at 18 06 56 |
| Screenshot 2021-06-28 at 18 08 40 | Screenshot 2021-06-28 at 18 07 15 |
| Screenshot 2021-06-28 at 18 09 04 | Screenshot 2021-06-28 at 18 10 12 |

## Things to check

- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] API release notes have been updated if necessary
- [ ] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Comment by frankieroberto** [comment]
@paulrobertlloyd I find the new "current tab + focus" state with the double underline a bit weird – could/should the yellow background colour fill the entirety of the click area instead, with the two underlines merging?

The new design also has no change when hovering over a current tab (previous one went slightly darker), but perhaps that's unnecessary anyway?

**Comment by paulrobertlloyd** [comment]
> I find the new "current tab + focus" state with the double underline a bit weird – could/should the yellow background colour fill the entirety of the click area instead, with the two underlines merging?

So do I, but arguably it’s more noticeable than what we are currently doing (thickening the bottom border on current focused). I’m inclined to embrace the inherent ~ugly~ utilitarian design aesthetic GDS have bestowed upon us.

> The new design also has no change when hovering over a current tab (previous one went slightly darker), but perhaps that's unnecessary anyway?

Yeah, I noticed that, it probably is unnecessary.

**Comment by duncanjbrown** [comment]
@frankieroberto and @paulrobertlloyd (when you're back!) please could you fix this one up?

**Comment by paulrobertlloyd** [comment]
Am raising the questions in this tread with GDS design team on x-gov Slack.

**Comment by paulrobertlloyd** [comment]
> I find the new "current tab + focus" state with the double underline a bit weird – could/should the yellow background colour fill the entirety of the click area instead, with the two underlines merging?

Feedback on this from GDS. Oliver Byford:

>  I’d say the focus states on the navigation are definitely intentional and were designed by the same designer who worked on the focus states. Historically we’ve generally tried to apply the focus state to text in the same way, with the black border immediately underneath and the yellow fairly tight around the text. We also use an `:after` pseudo element on the link so that we can have a ‘full height’ hit area whilst keeping the focus state tight.

Charlotte Downs:

> as Ollie mentioned we are trying to work out a way to make our focus styles consistent across similar components and interactions.

So this is an intentional design decision.

**Pull request closed without merging**
