### PR TITLE
[DO NOT MERGE] - Backfill NARIC UK name change

### PR DESCRIPTION
**Pull request by TobyRet**
## Context

This is a followup PR for https://github.com/DFE-Digital/apply-for-teacher-training/pull/4277 and should be deployed at the same time. *This needs to be rebased against master once https://github.com/DFE-Digital/apply-for-teacher-training/pull/4277  is merged*

## Changes proposed in this pull request

- Backfill the new `enic_reference` column
- Stop writing to the old `naric_reference` column
- Delete the old `naric_reference` column

## Guidance to review

The migrations have been split out into separate PRs so as not to deploy breaking changed to candidates. 
*Please review the final three commits in this PR*

Make sense?

## Link to Trello card

https://trello.com/c/2eAoTvSM/3130-uk-naric-name-change-to-uk-enic

## Things to check

- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] API release notes have been updated if necessary
- [ ] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-teacher-training/blob/master/docs/environment-variables.md#azure-hosting-devops-pipeline)

### CODE REVIEW

**Review by davidgisbey — APPROVED** [review]
Just needs a rebase once the other one is merged 👍 Are we deploying these out in 2 separate deploys?

**Comment by malcolmbaig** [comment]
I think this column rename needs to be organised into 3 deploys:


### Deploy 1
- Add new column
- Write to the new column 
- Backfill task for new column (written as a manual task that can be run after deploy)

### Deploy 2
- Reject old column from model
- Stop writing to old column

### Deploy 3
- Remove old column

Written quite quickly so happy to be challenged on any of this, but I think the above is how we avoid:

- errors for users
- any possibility of data inconsistency via the backfill

**Comment by davidgisbey** [comment]
That's the pattern we've previously followed 👍

**Comment by TobyRet** [comment]
Closing this PR - going to split up changes into separate deploys

**Pull request closed without merging**
