### PR TITLE
Add course full details text field

### PR DESCRIPTION
**Pull request by steventux**
## Context

We'd like to allow providers to give additional information about a course being full.

## Changes proposed in this pull request

Add a course full details field.

#### Additional textarea

image

#### Rejected application

image

## Link to Trello card

https://trello.com/c/Vso1SYpt/486-add-freetext-box-under-course-full-sr4r

## Things to check

- [x] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] If this code adds a column to the DB, decide whether it needs to be in analytics yml file or analytics blocklist
- [x] API release notes have been updated if necessary
- [x] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Comment by frankieroberto** [comment]
@steventux did we decide whether this text box should be optional ore required? 

If it's optional, we should probably add "(optional)" to the label.

**Comment by steventux** [comment]
@frankieroberto good catch. The Trello story does state _optional_. 
We don't currently support optional text boxes like this. `<groan>`

**Comment by frankieroberto** [comment]
> @frankieroberto good catch. The Trello story does state _optional_.
> We don't currently support optional text boxes like this. `<groan>`

I don't mind making it required - would be consistent with the other text boxes, and arguably might lead to more helpful information for the candidate?

**Comment by steventux** [comment]
@frankieroberto I've added the commits necessary to make this optional. But it's fairly simple to roll these back. Can you and @MylesJarvis make a call on this?

**Comment by frankieroberto** [comment]
Think we've agreed to keep it optional. 👍

**Comment by MylesJarvis** [comment]
yep - optional!

**Review by frankieroberto — APPROVED** [review]
Checked in review app. Works both with and without the text.

Can you update the screenshot to show the "(optional)" suffix? Then let's get this merged?

**Pull request merged**
