### PR TITLE
Show change conditions button in support

### PR DESCRIPTION
**Pull request by tomas-stefano**
## Context

Show change conditions button in support even if the offer doesn't have conditions.

### CODE REVIEW

**Comment by tomas-stefano** [comment]
[Support: Show a 'change conditions' button even when there are no conditions](https://trello.com/c/R83eDaiE/1236-support-show-a-change-conditions-button-even-when-there-are-no-conditions)

**Comment by frankieroberto** [comment]
@tomas-stefano any chance of a quick screenshot?

**Comment by tomas-stefano** [comment]
> @tomas-stefano any chance of a quick screenshot?

It will only show an empty row with the link. 
Screenshot 2023-03-27 at 17 07 21

**Comment by frankieroberto** [comment]
> > @tomas-stefano any chance of a quick screenshot?
> 
> It will only show an empty row with the link. Screenshot 2023-03-27 at 17 07 21

Maybe we could add some text saying “No conditions added” to the middle column of the row?

**Review by carlosmartinez — APPROVED** [review]

**Comment by tomas-stefano** [comment]
> No conditions adde

Done

**Pull request merged**
