### PR TITLE
Prevent candidate applying to closed course

### PR DESCRIPTION
**Pull request by inulty-dfe**
## Context

We are moving away from managing course application availablility from the vacancies of the CourseOptions and toward managing the course availability through the course open/closed.

We need to stop candidates applying to courses that are closed.

We have begin syncing `application_status` on the Course. Here we enforce the Candidat application submission based on the courses `application_status`

## Changes proposed in this pull request

 1. Prevent candidate from adding a closed course to their application choice
 2. Prevent candidate from submitting an application with a closed course

## Guidance to review

Other test scenarios to propose?

## Screenshots

|Adding closed course to application|Submitting application with closed course|
|---|---|
|image|image|

## Link to Trello card

[Trello Ticket](https://trello.com/c/5PtBd3gV/1516-implement-applicationstatus-in-places-where-appropriate)

## Things to check

- [ ] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] If this code adds a column to the DB, decide whether it needs to be in analytics yml file or analytics blocklist
- [ ] API release notes have been updated if necessary
- [ ] If it adds a significant user-facing change, is it documented in the [CHANGELOG](CHANGELOG.md)?
- [ ] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Comment by inulty-dfe** [comment]
[Prevent candidate applying to closed course](https://trello.com/c/5PtBd3gV/1516-prevent-candidate-applying-to-closed-course)

**Review by tomas-stefano — APPROVED** [review]
🚀 Can you ask someone from UCD to also take a look, please?

**Review by elceebee — APPROVED** [review]
👍

**Review by RebeccaCryan — COMMENTED** [review]
On the 'submitting application with closed course' screen - is it easy to update the text (I know it's what is already there, but I think it could be improved if there's an opportunity to do it easily)

Suggested:
You cannot submit this application because the course has closed.

**Review by inulty-dfe — COMMENTED** [review]
Adding context to commits

**Review by RebeccaCryan — APPROVED** [review]

**Pull request merged**
