### PR TITLE
Move vendorapi v1.0 specs to v1.0 folders

### PR DESCRIPTION
**Pull request by SamJamCul**
## Context
https://trello.com/c/LkmD9xRS/4775-amend-api-v1-directories

## Changes proposed in this pull request
Moving all specs that were effectively tied to v1.0 into their own v1.0 folder. 
Also ended up moving the interview spec to v1.1.
There's a base spec that seems version-independent

## Things to check

- [ ] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] API release notes have been updated if necessary
- [ ] Required environment variables have been updated [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

### CODE REVIEW

**Comment by despo** [comment]
@SamJamCul the versioning request spec is used to test the routing so it shouldn't be in v1.0

**Comment by SamJamCul** [comment]
> @SamJamCul the versioning request spec is used to test the routing so it shouldn't be in v1.0

I put it there because it made use of an endpoint that was introduced in v1.0 - would this test still work if somehow the version went below 1.0?

**Comment by SamJamCul** [comment]
> @SamJamCul the versioning request spec is used to test the routing so it shouldn't be in v1.0

@despo I've moved it back. I had originally put it in v1.0 as it used an endpoint introduced in 1.0, but it does make sense to try and keep it outside the version hierarchy, as it's testing versioning itself.

**Review by cwrw — COMMENTED** [review]
Looks good, I was thinking about the request specs, maybe we could move out authentication and throttling into the shared space and out of v1, what do you think?

**Comment by SamJamCul** [comment]
> Looks good, I was thinking about the request specs, maybe we could move out authentication and throttling into the shared space and out of v1, what do you think?

@cwrw Sure thing, I can see how they fit the convention.

**Comment by SamJamCul** [comment]
> Looks good, I was thinking about the request specs, maybe we could move out authentication and throttling into the shared space and out of v1, what do you think?

@cwrw I was also wondering if there's a case for modifying the versioning and throttling tests to use the ping endpoint, like the authentication spec does. It seems like a more appropriate route to use for tests that are for the api's core functionality

**Review by cwrw — APPROVED** [review]
👍

**Pull request merged**
